// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Payload associated with Business Glossary related log events.
public struct BusinessGlossaryEvent: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The log message.
  public var message: Swift.String = Swift.String()

  /// The type of the event.
  public var eventType: BusinessGlossaryEvent.EventType = BusinessGlossaryEvent.EventType()

  /// Name of the resource.
  public var resource: Swift.String = Swift.String()

  /// Initialize a new instance of `BusinessGlossaryEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BusinessGlossaryEvent().with { $0.message = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Type of glossary log event.
  public enum EventType: Codable, Equatable, Sendable {
    /// An unspecified event type.
    case unspecified
    /// Glossary create event.
    case glossaryCreate
    /// Glossary update event.
    case glossaryUpdate
    /// Glossary delete event.
    case glossaryDelete
    /// Glossary category create event.
    case glossaryCategoryCreate
    /// Glossary category update event.
    case glossaryCategoryUpdate
    /// Glossary category delete event.
    case glossaryCategoryDelete
    /// Glossary term create event.
    case glossaryTermCreate
    /// Glossary term update event.
    case glossaryTermUpdate
    /// Glossary term delete event.
    case glossaryTermDelete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .glossaryCreate: return 1
      case .glossaryUpdate: return 2
      case .glossaryDelete: return 3
      case .glossaryCategoryCreate: return 4
      case .glossaryCategoryUpdate: return 5
      case .glossaryCategoryDelete: return 6
      case .glossaryTermCreate: return 7
      case .glossaryTermUpdate: return 8
      case .glossaryTermDelete: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EVENT_TYPE_UNSPECIFIED"
      case .glossaryCreate: return "GLOSSARY_CREATE"
      case .glossaryUpdate: return "GLOSSARY_UPDATE"
      case .glossaryDelete: return "GLOSSARY_DELETE"
      case .glossaryCategoryCreate: return "GLOSSARY_CATEGORY_CREATE"
      case .glossaryCategoryUpdate: return "GLOSSARY_CATEGORY_UPDATE"
      case .glossaryCategoryDelete: return "GLOSSARY_CATEGORY_DELETE"
      case .glossaryTermCreate: return "GLOSSARY_TERM_CREATE"
      case .glossaryTermUpdate: return "GLOSSARY_TERM_UPDATE"
      case .glossaryTermDelete: return "GLOSSARY_TERM_DELETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "GLOSSARY_CREATE": self = .glossaryCreate
      case "GLOSSARY_UPDATE": self = .glossaryUpdate
      case "GLOSSARY_DELETE": self = .glossaryDelete
      case "GLOSSARY_CATEGORY_CREATE": self = .glossaryCategoryCreate
      case "GLOSSARY_CATEGORY_UPDATE": self = .glossaryCategoryUpdate
      case "GLOSSARY_CATEGORY_DELETE": self = .glossaryCategoryDelete
      case "GLOSSARY_TERM_CREATE": self = .glossaryTermCreate
      case "GLOSSARY_TERM_UPDATE": self = .glossaryTermUpdate
      case "GLOSSARY_TERM_DELETE": self = .glossaryTermDelete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .glossaryCreate
      case 2: self = .glossaryUpdate
      case 3: self = .glossaryDelete
      case 4: self = .glossaryCategoryCreate
      case 5: self = .glossaryCategoryUpdate
      case 6: self = .glossaryCategoryDelete
      case 7: self = .glossaryTermCreate
      case 8: self = .glossaryTermUpdate
      case 9: self = .glossaryTermDelete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .glossaryCreate: return try container.encode(1)
      case .glossaryUpdate: return try container.encode(2)
      case .glossaryDelete: return try container.encode(3)
      case .glossaryCategoryCreate: return try container.encode(4)
      case .glossaryCategoryUpdate: return try container.encode(5)
      case .glossaryCategoryDelete: return try container.encode(6)
      case .glossaryTermCreate: return try container.encode(7)
      case .glossaryTermUpdate: return try container.encode(8)
      case .glossaryTermDelete: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.BusinessGlossaryEvent"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
