// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol CatalogServiceStub: Sendable {
    func createEntryType(
      request: CreateEntryTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateEntryType(
      request: UpdateEntryTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEntryType(
      request: DeleteEntryTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listEntryTypes(
      request: ListEntryTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListEntryTypesResponse

    func getEntryType(
      request: GetEntryTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.EntryType

    func createAspectType(
      request: CreateAspectTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateAspectType(
      request: UpdateAspectTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAspectType(
      request: DeleteAspectTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listAspectTypes(
      request: ListAspectTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListAspectTypesResponse

    func getAspectType(
      request: GetAspectTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.AspectType

    func createEntryGroup(
      request: CreateEntryGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateEntryGroup(
      request: UpdateEntryGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteEntryGroup(
      request: DeleteEntryGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listEntryGroups(
      request: ListEntryGroupsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListEntryGroupsResponse

    func getEntryGroup(
      request: GetEntryGroupRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.EntryGroup

    func createEntry(
      request: CreateEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.Entry

    func updateEntry(
      request: UpdateEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.Entry

    func deleteEntry(
      request: DeleteEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.Entry

    func listEntries(
      request: ListEntriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListEntriesResponse

    func getEntry(
      request: GetEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.Entry

    func lookupEntry(
      request: LookupEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.Entry

    func modifyEntry(
      request: ModifyEntryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.Entry

    func searchEntries(
      request: SearchEntriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.SearchEntriesResponse

    func createMetadataJob(
      request: CreateMetadataJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getMetadataJob(
      request: GetMetadataJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.MetadataJob

    func listMetadataJobs(
      request: ListMetadataJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListMetadataJobsResponse

    func cancelMetadataJob(
      request: CancelMetadataJobRequest, options: GoogleGax.RequestOptions
    ) async throws

    func createEntryLink(
      request: CreateEntryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.EntryLink

    func updateEntryLink(
      request: UpdateEntryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.EntryLink

    func deleteEntryLink(
      request: DeleteEntryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.EntryLink

    func lookupEntryLinks(
      request: LookupEntryLinksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.LookupEntryLinksResponse

    func lookupContext(
      request: LookupContextRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.LookupContextResponse

    func getEntryLink(
      request: GetEntryLinkRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.EntryLink

    func createMetadataFeed(
      request: CreateMetadataFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getMetadataFeed(
      request: GetMetadataFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.MetadataFeed

    func listMetadataFeeds(
      request: ListMetadataFeedsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListMetadataFeedsResponse

    func deleteMetadataFeed(
      request: DeleteMetadataFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateMetadataFeed(
      request: UpdateMetadataFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}
