// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Content represents a user-visible notebook or a sql script
public struct Content: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The relative resource name of the content, of the form:
  /// projects/{project_id}/locations/{location_id}/lakes/{lake_id}/content/{content_id}
  public var name: Swift.String = Swift.String()

  /// Output only. System generated globally unique ID for the content. This ID
  /// will be different if the content is deleted and re-created with the same
  /// name.
  public var uid: Swift.String = Swift.String()

  /// Required. The path for the Content file, represented as directory
  /// structure. Unique within a lake. Limited to alphanumerics, hyphens,
  /// underscores, dots and slashes.
  public var path: Swift.String = Swift.String()

  /// Output only. Content creation time.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time when the content was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. User defined labels for the content.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. Description of the content.
  public var description: Swift.String = Swift.String()

  /// Only returned in `GetContent` requests and not in `ListContent` request.
  public var data: OneOf_Data? = nil

  /// Types of content
  public var content: OneOf_Content? = nil

  /// Initialize a new instance of `Content`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Content().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case uid = "uid"
    case path = "path"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case labels = "labels"
    case description = "description"
    case dataText = "dataText"
    case sqlScript = "sqlScript"
    case notebook = "notebook"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.uid = try container.decode(Swift.String.self, forKey: .uid)
    self.path = try container.decode(Swift.String.self, forKey: .path)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .updateTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.description = try container.decode(Swift.String.self, forKey: .description)

    var data: OneOf_Data? = nil
    let dataCheckAndSet = {
      if data != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'data'"
          ))
      }
      data = $0
    }
    if let dataText = try container.decodeIfPresent(Swift.String.self, forKey: .dataText) {
      try dataCheckAndSet(.dataText(dataText))
    }
    self.data = data

    var content: OneOf_Content? = nil
    let contentCheckAndSet = {
      if content != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'content'"))
      }
      content = $0
    }
    if let sqlScript = try container.decodeIfPresent(Content.SqlScript?.self, forKey: .sqlScript) {
      try contentCheckAndSet(.sqlScript(sqlScript))
    }
    if let notebook = try container.decodeIfPresent(Content.Notebook?.self, forKey: .notebook) {
      try contentCheckAndSet(.notebook(notebook))
    }
    self.content = content
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.description, forKey: .description)

    if let choice = self.data {
      switch choice {
      case .dataText(let value):
        try container.encode(value, forKey: .dataText)
      }
    }

    if let choice = self.content {
      switch choice {
      case .sqlScript(let value):
        try container.encode(value, forKey: .sqlScript)
      case .notebook(let value):
        try container.encode(value, forKey: .notebook)
      }
    }
  }

  /// Configuration for the Sql Script content.
  public struct SqlScript: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Query Engine to be used for the Sql Query.
    public var engine: Content.SqlScript.QueryEngine = Content.SqlScript.QueryEngine()

    /// Initialize a new instance of `SqlScript`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SqlScript().with { $0.engine = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Query Engine Type of the SQL Script.
    public enum QueryEngine: Codable, Equatable, Sendable {
      /// Value was unspecified.
      case unspecified
      /// Spark SQL Query.
      case spark
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .spark: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "QUERY_ENGINE_UNSPECIFIED"
        case .spark: return "SPARK"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:QueryEngine/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "QUERY_ENGINE_UNSPECIFIED": self = .unspecified
        case "SPARK": self = .spark
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:QueryEngine/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 2: self = .spark
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .spark: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.Content.SqlScript"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configuration for Notebook content.
  public struct Notebook: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Kernel Type of the notebook.
    public var kernelType: Content.Notebook.KernelType = Content.Notebook.KernelType()

    /// Initialize a new instance of `Notebook`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Notebook().with { $0.kernelType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Kernel Type of the Jupyter notebook.
    public enum KernelType: Codable, Equatable, Sendable {
      /// Kernel Type unspecified.
      case unspecified
      /// Python 3 Kernel.
      case python3
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .python3: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "KERNEL_TYPE_UNSPECIFIED"
        case .python3: return "PYTHON3"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:KernelType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "KERNEL_TYPE_UNSPECIFIED": self = .unspecified
        case "PYTHON3": self = .python3
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:KernelType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .python3
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .python3: return try container.encode(1)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.Content.Notebook"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Only returned in `GetContent` requests and not in `ListContent` request.
  public enum OneOf_Data: Codable, Equatable, Sendable {
    /// Required. Content data in string format.
    case dataText(Swift.String)
  }

  /// Types of content
  public enum OneOf_Content: Codable, Equatable, Sendable {
    /// Sql Script related configurations.
    indirect case sqlScript(Content.SqlScript?)
    /// Notebook related configurations.
    indirect case notebook(Content.Notebook?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.Content"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
