// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Create Entry request.
public struct CreateEntryRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the parent Entry Group:
  /// `projects/{project}/locations/{location}/entryGroups/{entry_group}`.
  public var parent: Swift.String = Swift.String()

  /// Required. Entry identifier. It has to be unique within an Entry Group.
  ///
  /// Entries corresponding to Google Cloud resources use an Entry ID format
  /// based on [full resource
  /// names](https://cloud.google.com/apis/design/resource_names#full_resource_name).
  /// The format is a full resource name of the resource without the
  /// prefix double slashes in the API service name part of the full resource
  /// name. This allows retrieval of entries using their associated resource
  /// name.
  ///
  /// For example, if the full resource name of a resource is
  /// `//library.googleapis.com/shelves/shelf1/books/book2`,
  /// then the suggested entry_id is
  /// `library.googleapis.com/shelves/shelf1/books/book2`.
  ///
  /// It is also suggested to follow the same convention for entries
  /// corresponding to resources from providers or systems other than Google
  /// Cloud.
  ///
  /// The maximum size of the field is 4000 characters.
  public var entryId: Swift.String = Swift.String()

  /// Required. Entry resource.
  public var entry: Entry? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateEntryRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateEntryRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let entryId = CodingKeys(stringValue: "entryId")
    static let entry = CodingKeys(stringValue: "entry")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "entryId",
      "entry",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entryId) {
      self.entryId = value
    }
    self.entry = try container.decodeIfPresent(Entry.self, forKey: .entry)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.entryId, forKey: .entryId)
    try container.encodeIfPresent(self.entry, forKey: .entry)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.CreateEntryRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
