// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Create DataTaxonomy request.
@available(*, deprecated)
public struct CreateDataTaxonomyRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var parent: Swift.String = Swift.String()

  /// Required. DataTaxonomy identifier.
  /// * Must contain only lowercase letters, numbers and hyphens.
  /// * Must start with a letter.
  /// * Must be between 1-63 characters.
  /// * Must end with a number or a letter.
  /// * Must be unique within the Project.
  public var dataTaxonomyId: Swift.String = Swift.String()

  /// Required. DataTaxonomy resource.
  public var dataTaxonomy: DataTaxonomy? = nil

  /// Optional. Only validate the request, but do not perform mutations.
  /// The default is false.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreateDataTaxonomyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateDataTaxonomyRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.CreateDataTaxonomyRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
