// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) import GoogleCloudLocation
@_spi(GoogleCloudInternal) import GoogleIAMV1
@_spi(GoogleCloudInternal) import GoogleLongRunning
@_spi(GoogleCloudInternal) import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

/// DataTaxonomyService enables attribute-based governance. The resources
/// currently offered include DataTaxonomy and DataAttribute.
///
/// @Snippet(path: "DataTaxonomyServiceQuickstart")
@available(*, deprecated)
public final class DataTaxonomyServiceClient: Clients.DataTaxonomyServiceProtocol, Sendable {
  let inner: any Clients.DataTaxonomyServiceStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `DataTaxonomyServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.DataTaxonomyServiceStub = try Clients.DataTaxonomyServiceTransport(
      options)
    inner = Clients.DataTaxonomyServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DataTaxonomyServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Create a DataTaxonomy resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_CreateDataTaxonomy")
  @available(*, deprecated)
  public func createDataTaxonomy(
    request: CreateDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createDataTaxonomy(request: request, options: options)
  }

  /// Create a DataTaxonomy resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_CreateDataTaxonomy")
  @available(*, deprecated)
  public func createDataTaxonomy(
    withPolling: CreateDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DataTaxonomy>.State in
      return try op._extractStatus(DataTaxonomy.self)
    }
    let rawOp = try await self.createDataTaxonomy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataTaxonomy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a DataTaxonomy resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_UpdateDataTaxonomy")
  @available(*, deprecated)
  public func updateDataTaxonomy(
    request: UpdateDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateDataTaxonomy(request: request, options: options)
  }

  /// Updates a DataTaxonomy resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_UpdateDataTaxonomy")
  @available(*, deprecated)
  public func updateDataTaxonomy(
    withPolling: UpdateDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DataTaxonomy>.State in
      return try op._extractStatus(DataTaxonomy.self)
    }
    let rawOp = try await self.updateDataTaxonomy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataTaxonomy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a DataTaxonomy resource. All attributes within the DataTaxonomy
  /// must be deleted before the DataTaxonomy can be deleted.
  ///
  /// @Snippet(path: "DataTaxonomyService_DeleteDataTaxonomy")
  @available(*, deprecated)
  public func deleteDataTaxonomy(
    request: DeleteDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteDataTaxonomy(request: request, options: options)
  }

  /// Deletes a DataTaxonomy resource. All attributes within the DataTaxonomy
  /// must be deleted before the DataTaxonomy can be deleted.
  ///
  /// @Snippet(path: "DataTaxonomyService_DeleteDataTaxonomy")
  @available(*, deprecated)
  public func deleteDataTaxonomy(
    withPolling: DeleteDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteDataTaxonomy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists DataTaxonomy resources in a project and location.
  ///
  /// @Snippet(path: "DataTaxonomyService_ListDataTaxonomies")
  @available(*, deprecated)
  public func listDataTaxonomies(
    request: ListDataTaxonomiesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.ListDataTaxonomiesResponse {
    try await self.inner.listDataTaxonomies(request: request, options: options)
  }

  /// Lists DataTaxonomy resources in a project and location.
  ///
  /// @Snippet(path: "DataTaxonomyService_ListDataTaxonomies")
  @available(*, deprecated)
  public func listDataTaxonomies(
    byItem: ListDataTaxonomiesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<DataTaxonomy, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDataplexV1.ListDataTaxonomiesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDataTaxonomies(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a DataTaxonomy resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_GetDataTaxonomy")
  @available(*, deprecated)
  public func getDataTaxonomy(
    request: GetDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.DataTaxonomy {
    try await self.inner.getDataTaxonomy(request: request, options: options)
  }

  /// Create a DataAttributeBinding resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_CreateDataAttributeBinding")
  @available(*, deprecated)
  public func createDataAttributeBinding(
    request: CreateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createDataAttributeBinding(request: request, options: options)
  }

  /// Create a DataAttributeBinding resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_CreateDataAttributeBinding")
  @available(*, deprecated)
  public func createDataAttributeBinding(
    withPolling: CreateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DataAttributeBinding>.State in
      return try op._extractStatus(DataAttributeBinding.self)
    }
    let rawOp = try await self.createDataAttributeBinding(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataAttributeBinding>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a DataAttributeBinding resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_UpdateDataAttributeBinding")
  @available(*, deprecated)
  public func updateDataAttributeBinding(
    request: UpdateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateDataAttributeBinding(request: request, options: options)
  }

  /// Updates a DataAttributeBinding resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_UpdateDataAttributeBinding")
  @available(*, deprecated)
  public func updateDataAttributeBinding(
    withPolling: UpdateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DataAttributeBinding>.State in
      return try op._extractStatus(DataAttributeBinding.self)
    }
    let rawOp = try await self.updateDataAttributeBinding(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataAttributeBinding>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a DataAttributeBinding resource. All attributes within the
  /// DataAttributeBinding must be deleted before the DataAttributeBinding can be
  /// deleted.
  ///
  /// @Snippet(path: "DataTaxonomyService_DeleteDataAttributeBinding")
  @available(*, deprecated)
  public func deleteDataAttributeBinding(
    request: DeleteDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteDataAttributeBinding(request: request, options: options)
  }

  /// Deletes a DataAttributeBinding resource. All attributes within the
  /// DataAttributeBinding must be deleted before the DataAttributeBinding can be
  /// deleted.
  ///
  /// @Snippet(path: "DataTaxonomyService_DeleteDataAttributeBinding")
  @available(*, deprecated)
  public func deleteDataAttributeBinding(
    withPolling: DeleteDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteDataAttributeBinding(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists DataAttributeBinding resources in a project and location.
  ///
  /// @Snippet(path: "DataTaxonomyService_ListDataAttributeBindings")
  @available(*, deprecated)
  public func listDataAttributeBindings(
    request: ListDataAttributeBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.ListDataAttributeBindingsResponse {
    try await self.inner.listDataAttributeBindings(request: request, options: options)
  }

  /// Lists DataAttributeBinding resources in a project and location.
  ///
  /// @Snippet(path: "DataTaxonomyService_ListDataAttributeBindings")
  @available(*, deprecated)
  public func listDataAttributeBindings(
    byItem: ListDataAttributeBindingsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<DataAttributeBinding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDataplexV1.ListDataAttributeBindingsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listDataAttributeBindings(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a DataAttributeBinding resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_GetDataAttributeBinding")
  @available(*, deprecated)
  public func getDataAttributeBinding(
    request: GetDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.DataAttributeBinding {
    try await self.inner.getDataAttributeBinding(request: request, options: options)
  }

  /// Create a DataAttribute resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_CreateDataAttribute")
  @available(*, deprecated)
  public func createDataAttribute(
    request: CreateDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createDataAttribute(request: request, options: options)
  }

  /// Create a DataAttribute resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_CreateDataAttribute")
  @available(*, deprecated)
  public func createDataAttribute(
    withPolling: CreateDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataAttribute> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DataAttribute>.State in
      return try op._extractStatus(DataAttribute.self)
    }
    let rawOp = try await self.createDataAttribute(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataAttribute>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Updates a DataAttribute resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_UpdateDataAttribute")
  @available(*, deprecated)
  public func updateDataAttribute(
    request: UpdateDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateDataAttribute(request: request, options: options)
  }

  /// Updates a DataAttribute resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_UpdateDataAttribute")
  @available(*, deprecated)
  public func updateDataAttribute(
    withPolling: UpdateDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataAttribute> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<DataAttribute>.State in
      return try op._extractStatus(DataAttribute.self)
    }
    let rawOp = try await self.updateDataAttribute(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataAttribute>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a Data Attribute resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_DeleteDataAttribute")
  @available(*, deprecated)
  public func deleteDataAttribute(
    request: DeleteDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteDataAttribute(request: request, options: options)
  }

  /// Deletes a Data Attribute resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_DeleteDataAttribute")
  @available(*, deprecated)
  public func deleteDataAttribute(
    withPolling: DeleteDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State
      in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteDataAttribute(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists Data Attribute resources in a DataTaxonomy.
  ///
  /// @Snippet(path: "DataTaxonomyService_ListDataAttributes")
  @available(*, deprecated)
  public func listDataAttributes(
    request: ListDataAttributesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.ListDataAttributesResponse {
    try await self.inner.listDataAttributes(request: request, options: options)
  }

  /// Lists Data Attribute resources in a DataTaxonomy.
  ///
  /// @Snippet(path: "DataTaxonomyService_ListDataAttributes")
  @available(*, deprecated)
  public func listDataAttributes(
    byItem: ListDataAttributesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<DataAttribute, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDataplexV1.ListDataAttributesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDataAttributes(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Retrieves a Data Attribute resource.
  ///
  /// @Snippet(path: "DataTaxonomyService_GetDataAttribute")
  @available(*, deprecated)
  public func getDataAttribute(
    request: GetDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.DataAttribute {
    try await self.inner.getDataAttribute(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "DataTaxonomyService_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// This method lists locations based on the resource scope provided in
  /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
  /// **Global locations**: If `name` is empty, the method lists the
  /// public locations available to all projects. * **Project-specific
  /// locations**: If `name` follows the format
  /// `projects/{project}`, the method lists locations visible to that
  /// specific project. This includes public, private, or other
  /// project-specific locations enabled for the project.
  ///
  /// For gRPC and client library implementations, the resource name is
  /// passed as the `name` field. For direct service calls, the resource
  /// name is
  /// incorporated into the request path based on the specific service
  /// implementation and version.
  ///
  /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
  ///
  /// @Snippet(path: "DataTaxonomyService_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "DataTaxonomyService_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Sets the access control policy on the specified resource. Replaces
  /// any existing policy.
  ///
  /// Can return `NOT_FOUND`, `INVALID_ARGUMENT`, and `PERMISSION_DENIED`
  /// errors.
  ///
  /// @Snippet(path: "DataTaxonomyService_SetIamPolicy")
  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.setIamPolicy(request: request, options: options)
  }

  /// Gets the access control policy for a resource. Returns an empty policy
  /// if the resource exists and does not have a policy set.
  ///
  /// @Snippet(path: "DataTaxonomyService_GetIamPolicy")
  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    try await self.inner.getIamPolicy(request: request, options: options)
  }

  /// Returns permissions that a caller has on the specified resource. If the
  /// resource does not exist, this will return an empty set of
  /// permissions, not a `NOT_FOUND` error.
  ///
  /// Note: This operation is designed to be used for building
  /// permission-aware UIs and command-line tools, not for authorization
  /// checking. This operation may "fail open" without warning.
  ///
  /// @Snippet(path: "DataTaxonomyService_TestIamPermissions")
  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    try await self.inner.testIamPermissions(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataTaxonomyService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataTaxonomyService_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataTaxonomyService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataTaxonomyService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "DataTaxonomyService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DataTaxonomyServiceClient`.
  ///
  /// To mock `DataTaxonomyServiceClient` change your functions to receive
  /// `some DataTaxonomyServiceProtocol` or `any DataTaxonomyServiceProtocol`
  /// and pass a mock implementation in your tests.
  @available(*, deprecated)
  public protocol DataTaxonomyServiceProtocol {
    /// See `DataTaxonomyServiceClient.createDataTaxonomy`.
    @available(*, deprecated)
    func createDataTaxonomy(request: CreateDataTaxonomyRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.createDataTaxonomy`.
    @available(*, deprecated)
    func createDataTaxonomy(withPolling: CreateDataTaxonomyRequest) async throws -> any GoogleGax
      .PollableOperation<DataTaxonomy>

    /// See `DataTaxonomyServiceClient.createDataTaxonomy`.
    @available(*, deprecated)
    func createDataTaxonomy(
      parent: Swift.String,
      dataTaxonomy: DataTaxonomy?,
      dataTaxonomyId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy>

    /// See `DataTaxonomyServiceClient.updateDataTaxonomy`.
    @available(*, deprecated)
    func updateDataTaxonomy(request: UpdateDataTaxonomyRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.updateDataTaxonomy`.
    @available(*, deprecated)
    func updateDataTaxonomy(withPolling: UpdateDataTaxonomyRequest) async throws -> any GoogleGax
      .PollableOperation<DataTaxonomy>

    /// See `DataTaxonomyServiceClient.updateDataTaxonomy`.
    @available(*, deprecated)
    func updateDataTaxonomy(
      dataTaxonomy: DataTaxonomy?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy>

    /// See `DataTaxonomyServiceClient.deleteDataTaxonomy`.
    @available(*, deprecated)
    func deleteDataTaxonomy(request: DeleteDataTaxonomyRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.deleteDataTaxonomy`.
    @available(*, deprecated)
    func deleteDataTaxonomy(withPolling: DeleteDataTaxonomyRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.deleteDataTaxonomy`.
    @available(*, deprecated)
    func deleteDataTaxonomy(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.listDataTaxonomies`.
    @available(*, deprecated)
    func listDataTaxonomies(request: ListDataTaxonomiesRequest) async throws
      -> GoogleCloudDataplexV1.ListDataTaxonomiesResponse

    /// See `DataTaxonomyServiceClient.listDataTaxonomies`.
    @available(*, deprecated)
    func listDataTaxonomies(
      byItem: ListDataTaxonomiesRequest
    ) throws -> any AsyncSequence<DataTaxonomy, Swift.Error>

    /// See `DataTaxonomyServiceClient.listDataTaxonomies`.
    @available(*, deprecated)
    func listDataTaxonomies(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DataTaxonomy, Swift.Error>

    /// See `DataTaxonomyServiceClient.getDataTaxonomy`.
    @available(*, deprecated)
    func getDataTaxonomy(request: GetDataTaxonomyRequest) async throws
      -> GoogleCloudDataplexV1.DataTaxonomy

    /// See `DataTaxonomyServiceClient.getDataTaxonomy`.
    @available(*, deprecated)
    func getDataTaxonomy(
      name: Swift.String,
    ) async throws -> GoogleCloudDataplexV1.DataTaxonomy

    /// See `DataTaxonomyServiceClient.createDataAttributeBinding`.
    @available(*, deprecated)
    func createDataAttributeBinding(request: CreateDataAttributeBindingRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.createDataAttributeBinding`.
    @available(*, deprecated)
    func createDataAttributeBinding(withPolling: CreateDataAttributeBindingRequest) async throws
      -> any GoogleGax.PollableOperation<DataAttributeBinding>

    /// See `DataTaxonomyServiceClient.createDataAttributeBinding`.
    @available(*, deprecated)
    func createDataAttributeBinding(
      parent: Swift.String,
      dataAttributeBinding: DataAttributeBinding?,
      dataAttributeBindingId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding>

    /// See `DataTaxonomyServiceClient.updateDataAttributeBinding`.
    @available(*, deprecated)
    func updateDataAttributeBinding(request: UpdateDataAttributeBindingRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.updateDataAttributeBinding`.
    @available(*, deprecated)
    func updateDataAttributeBinding(withPolling: UpdateDataAttributeBindingRequest) async throws
      -> any GoogleGax.PollableOperation<DataAttributeBinding>

    /// See `DataTaxonomyServiceClient.updateDataAttributeBinding`.
    @available(*, deprecated)
    func updateDataAttributeBinding(
      dataAttributeBinding: DataAttributeBinding?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding>

    /// See `DataTaxonomyServiceClient.deleteDataAttributeBinding`.
    @available(*, deprecated)
    func deleteDataAttributeBinding(request: DeleteDataAttributeBindingRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.deleteDataAttributeBinding`.
    @available(*, deprecated)
    func deleteDataAttributeBinding(withPolling: DeleteDataAttributeBindingRequest) async throws
      -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.deleteDataAttributeBinding`.
    @available(*, deprecated)
    func deleteDataAttributeBinding(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.listDataAttributeBindings`.
    @available(*, deprecated)
    func listDataAttributeBindings(request: ListDataAttributeBindingsRequest) async throws
      -> GoogleCloudDataplexV1.ListDataAttributeBindingsResponse

    /// See `DataTaxonomyServiceClient.listDataAttributeBindings`.
    @available(*, deprecated)
    func listDataAttributeBindings(
      byItem: ListDataAttributeBindingsRequest
    ) throws -> any AsyncSequence<DataAttributeBinding, Swift.Error>

    /// See `DataTaxonomyServiceClient.listDataAttributeBindings`.
    @available(*, deprecated)
    func listDataAttributeBindings(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DataAttributeBinding, Swift.Error>

    /// See `DataTaxonomyServiceClient.getDataAttributeBinding`.
    @available(*, deprecated)
    func getDataAttributeBinding(request: GetDataAttributeBindingRequest) async throws
      -> GoogleCloudDataplexV1.DataAttributeBinding

    /// See `DataTaxonomyServiceClient.getDataAttributeBinding`.
    @available(*, deprecated)
    func getDataAttributeBinding(
      name: Swift.String,
    ) async throws -> GoogleCloudDataplexV1.DataAttributeBinding

    /// See `DataTaxonomyServiceClient.createDataAttribute`.
    @available(*, deprecated)
    func createDataAttribute(request: CreateDataAttributeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.createDataAttribute`.
    @available(*, deprecated)
    func createDataAttribute(withPolling: CreateDataAttributeRequest) async throws -> any GoogleGax
      .PollableOperation<DataAttribute>

    /// See `DataTaxonomyServiceClient.createDataAttribute`.
    @available(*, deprecated)
    func createDataAttribute(
      parent: Swift.String,
      dataAttribute: DataAttribute?,
      dataAttributeId: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<DataAttribute>

    /// See `DataTaxonomyServiceClient.updateDataAttribute`.
    @available(*, deprecated)
    func updateDataAttribute(request: UpdateDataAttributeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.updateDataAttribute`.
    @available(*, deprecated)
    func updateDataAttribute(withPolling: UpdateDataAttributeRequest) async throws -> any GoogleGax
      .PollableOperation<DataAttribute>

    /// See `DataTaxonomyServiceClient.updateDataAttribute`.
    @available(*, deprecated)
    func updateDataAttribute(
      dataAttribute: DataAttribute?,
      updateMask: GoogleWKT.FieldMask?,
    ) async throws -> any GoogleGax.PollableOperation<DataAttribute>

    /// See `DataTaxonomyServiceClient.deleteDataAttribute`.
    @available(*, deprecated)
    func deleteDataAttribute(request: DeleteDataAttributeRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.deleteDataAttribute`.
    @available(*, deprecated)
    func deleteDataAttribute(withPolling: DeleteDataAttributeRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.deleteDataAttribute`.
    @available(*, deprecated)
    func deleteDataAttribute(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.listDataAttributes`.
    @available(*, deprecated)
    func listDataAttributes(request: ListDataAttributesRequest) async throws
      -> GoogleCloudDataplexV1.ListDataAttributesResponse

    /// See `DataTaxonomyServiceClient.listDataAttributes`.
    @available(*, deprecated)
    func listDataAttributes(
      byItem: ListDataAttributesRequest
    ) throws -> any AsyncSequence<DataAttribute, Swift.Error>

    /// See `DataTaxonomyServiceClient.listDataAttributes`.
    @available(*, deprecated)
    func listDataAttributes(
      parent: Swift.String,
    ) throws -> any AsyncSequence<DataAttribute, Swift.Error>

    /// See `DataTaxonomyServiceClient.getDataAttribute`.
    @available(*, deprecated)
    func getDataAttribute(request: GetDataAttributeRequest) async throws
      -> GoogleCloudDataplexV1.DataAttribute

    /// See `DataTaxonomyServiceClient.getDataAttribute`.
    @available(*, deprecated)
    func getDataAttribute(
      name: Swift.String,
    ) async throws -> GoogleCloudDataplexV1.DataAttribute

    /// See `DataTaxonomyServiceClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `DataTaxonomyServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `DataTaxonomyServiceClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `DataTaxonomyServiceClient.setIamPolicy`.
    func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `DataTaxonomyServiceClient.getIamPolicy`.
    func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws -> GoogleIAMV1.Policy

    /// See `DataTaxonomyServiceClient.testIamPermissions`.
    func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
      -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `DataTaxonomyServiceClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `DataTaxonomyServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DataTaxonomyServiceClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DataTaxonomyServiceClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `DataTaxonomyServiceClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `DataTaxonomyServiceClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `DataTaxonomyServiceClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `DataTaxonomyServiceClient.createDataTaxonomy`.
    @available(*, deprecated)
    func createDataTaxonomy(
      request: CreateDataTaxonomyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.createDataTaxonomy`.
    @available(*, deprecated)
    func createDataTaxonomy(
      withPolling: CreateDataTaxonomyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy>

    /// See `DataTaxonomyServiceClient.updateDataTaxonomy`.
    @available(*, deprecated)
    func updateDataTaxonomy(
      request: UpdateDataTaxonomyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.updateDataTaxonomy`.
    @available(*, deprecated)
    func updateDataTaxonomy(
      withPolling: UpdateDataTaxonomyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy>

    /// See `DataTaxonomyServiceClient.deleteDataTaxonomy`.
    @available(*, deprecated)
    func deleteDataTaxonomy(
      request: DeleteDataTaxonomyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.deleteDataTaxonomy`.
    @available(*, deprecated)
    func deleteDataTaxonomy(
      withPolling: DeleteDataTaxonomyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.listDataTaxonomies`.
    @available(*, deprecated)
    func listDataTaxonomies(
      request: ListDataTaxonomiesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListDataTaxonomiesResponse

    /// See `DataTaxonomyServiceClient.listDataTaxonomies`.
    @available(*, deprecated)
    func listDataTaxonomies(
      byItem: ListDataTaxonomiesRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<DataTaxonomy, Swift.Error>

    /// See `DataTaxonomyServiceClient.getDataTaxonomy`.
    @available(*, deprecated)
    func getDataTaxonomy(
      request: GetDataTaxonomyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.DataTaxonomy

    /// See `DataTaxonomyServiceClient.createDataAttributeBinding`.
    @available(*, deprecated)
    func createDataAttributeBinding(
      request: CreateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.createDataAttributeBinding`.
    @available(*, deprecated)
    func createDataAttributeBinding(
      withPolling: CreateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding>

    /// See `DataTaxonomyServiceClient.updateDataAttributeBinding`.
    @available(*, deprecated)
    func updateDataAttributeBinding(
      request: UpdateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.updateDataAttributeBinding`.
    @available(*, deprecated)
    func updateDataAttributeBinding(
      withPolling: UpdateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding>

    /// See `DataTaxonomyServiceClient.deleteDataAttributeBinding`.
    @available(*, deprecated)
    func deleteDataAttributeBinding(
      request: DeleteDataAttributeBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.deleteDataAttributeBinding`.
    @available(*, deprecated)
    func deleteDataAttributeBinding(
      withPolling: DeleteDataAttributeBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.listDataAttributeBindings`.
    @available(*, deprecated)
    func listDataAttributeBindings(
      request: ListDataAttributeBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListDataAttributeBindingsResponse

    /// See `DataTaxonomyServiceClient.listDataAttributeBindings`.
    @available(*, deprecated)
    func listDataAttributeBindings(
      byItem: ListDataAttributeBindingsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<DataAttributeBinding, Swift.Error>

    /// See `DataTaxonomyServiceClient.getDataAttributeBinding`.
    @available(*, deprecated)
    func getDataAttributeBinding(
      request: GetDataAttributeBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.DataAttributeBinding

    /// See `DataTaxonomyServiceClient.createDataAttribute`.
    @available(*, deprecated)
    func createDataAttribute(
      request: CreateDataAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.createDataAttribute`.
    @available(*, deprecated)
    func createDataAttribute(
      withPolling: CreateDataAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<DataAttribute>

    /// See `DataTaxonomyServiceClient.updateDataAttribute`.
    @available(*, deprecated)
    func updateDataAttribute(
      request: UpdateDataAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.updateDataAttribute`.
    @available(*, deprecated)
    func updateDataAttribute(
      withPolling: UpdateDataAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<DataAttribute>

    /// See `DataTaxonomyServiceClient.deleteDataAttribute`.
    @available(*, deprecated)
    func deleteDataAttribute(
      request: DeleteDataAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DataTaxonomyServiceClient.deleteDataAttribute`.
    @available(*, deprecated)
    func deleteDataAttribute(
      withPolling: DeleteDataAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `DataTaxonomyServiceClient.listDataAttributes`.
    @available(*, deprecated)
    func listDataAttributes(
      request: ListDataAttributesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.ListDataAttributesResponse

    /// See `DataTaxonomyServiceClient.listDataAttributes`.
    @available(*, deprecated)
    func listDataAttributes(
      byItem: ListDataAttributesRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<DataAttribute, Swift.Error>

    /// See `DataTaxonomyServiceClient.getDataAttribute`.
    @available(*, deprecated)
    func getDataAttribute(
      request: GetDataAttributeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDataplexV1.DataAttribute

    /// See `DataTaxonomyServiceClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `DataTaxonomyServiceClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `DataTaxonomyServiceClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `DataTaxonomyServiceClient.setIamPolicy`.
    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `DataTaxonomyServiceClient.getIamPolicy`.
    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    /// See `DataTaxonomyServiceClient.testIamPermissions`.
    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    /// See `DataTaxonomyServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DataTaxonomyServiceClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DataTaxonomyServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `DataTaxonomyServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
@available(*, deprecated)
extension Clients.DataTaxonomyServiceProtocol {
  @available(*, deprecated)
  public func createDataTaxonomy(request: CreateDataTaxonomyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createDataTaxonomy(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createDataTaxonomy(
    request: CreateDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createDataTaxonomy(withPolling: CreateDataTaxonomyRequest) async throws
    -> any GoogleGax.PollableOperation<DataTaxonomy>
  {
    try await self.createDataTaxonomy(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func createDataTaxonomy(
    withPolling: CreateDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataTaxonomy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func createDataTaxonomy(
    parent: Swift.String,
    dataTaxonomy: DataTaxonomy?,
    dataTaxonomyId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy> {
    let request = CreateDataTaxonomyRequest().with {
      $0.parent = parent
      $0.dataTaxonomy = dataTaxonomy
      $0.dataTaxonomyId = dataTaxonomyId
    }
    return try await self.createDataTaxonomy(withPolling: request)
  }

  @available(*, deprecated)
  public func updateDataTaxonomy(request: UpdateDataTaxonomyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateDataTaxonomy(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateDataTaxonomy(
    request: UpdateDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateDataTaxonomy(withPolling: UpdateDataTaxonomyRequest) async throws
    -> any GoogleGax.PollableOperation<DataTaxonomy>
  {
    try await self.updateDataTaxonomy(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func updateDataTaxonomy(
    withPolling: UpdateDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataTaxonomy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func updateDataTaxonomy(
    dataTaxonomy: DataTaxonomy?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<DataTaxonomy> {
    let request = UpdateDataTaxonomyRequest().with {
      $0.dataTaxonomy = dataTaxonomy
      $0.updateMask = updateMask
    }
    return try await self.updateDataTaxonomy(withPolling: request)
  }

  @available(*, deprecated)
  public func deleteDataTaxonomy(request: DeleteDataTaxonomyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteDataTaxonomy(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteDataTaxonomy(
    request: DeleteDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteDataTaxonomy(withPolling: DeleteDataTaxonomyRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteDataTaxonomy(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func deleteDataTaxonomy(
    withPolling: DeleteDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func deleteDataTaxonomy(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteDataTaxonomyRequest().with {
      $0.name = name
    }
    return try await self.deleteDataTaxonomy(withPolling: request)
  }

  @available(*, deprecated)
  public func listDataTaxonomies(request: ListDataTaxonomiesRequest) async throws
    -> GoogleCloudDataplexV1.ListDataTaxonomiesResponse
  {
    try await self.listDataTaxonomies(request: request, options: .init())
  }

  @available(*, deprecated)
  public func listDataTaxonomies(
    request: ListDataTaxonomiesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.ListDataTaxonomiesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func listDataTaxonomies(
    byItem: ListDataTaxonomiesRequest
  ) throws -> any AsyncSequence<DataTaxonomy, Swift.Error> {
    try self.listDataTaxonomies(byItem: byItem, options: .init())
  }

  @available(*, deprecated)
  public func listDataTaxonomies(
    byItem: ListDataTaxonomiesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<DataTaxonomy, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDataplexV1.ListDataTaxonomiesResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  @available(*, deprecated)
  public func listDataTaxonomies(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DataTaxonomy, Swift.Error> {
    let request = ListDataTaxonomiesRequest().with {
      $0.parent = parent
    }
    return try self.listDataTaxonomies(byItem: request)
  }

  @available(*, deprecated)
  public func getDataTaxonomy(request: GetDataTaxonomyRequest) async throws
    -> GoogleCloudDataplexV1.DataTaxonomy
  {
    try await self.getDataTaxonomy(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getDataTaxonomy(
    request: GetDataTaxonomyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.DataTaxonomy {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getDataTaxonomy(
    name: Swift.String,
  ) async throws -> GoogleCloudDataplexV1.DataTaxonomy {
    let request = GetDataTaxonomyRequest().with {
      $0.name = name
    }
    return try await self.getDataTaxonomy(request: request)
  }

  @available(*, deprecated)
  public func createDataAttributeBinding(request: CreateDataAttributeBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createDataAttributeBinding(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createDataAttributeBinding(
    request: CreateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createDataAttributeBinding(withPolling: CreateDataAttributeBindingRequest)
    async throws -> any GoogleGax.PollableOperation<DataAttributeBinding>
  {
    try await self.createDataAttributeBinding(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func createDataAttributeBinding(
    withPolling: CreateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataAttributeBinding>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func createDataAttributeBinding(
    parent: Swift.String,
    dataAttributeBinding: DataAttributeBinding?,
    dataAttributeBindingId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding> {
    let request = CreateDataAttributeBindingRequest().with {
      $0.parent = parent
      $0.dataAttributeBinding = dataAttributeBinding
      $0.dataAttributeBindingId = dataAttributeBindingId
    }
    return try await self.createDataAttributeBinding(withPolling: request)
  }

  @available(*, deprecated)
  public func updateDataAttributeBinding(request: UpdateDataAttributeBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateDataAttributeBinding(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateDataAttributeBinding(
    request: UpdateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateDataAttributeBinding(withPolling: UpdateDataAttributeBindingRequest)
    async throws -> any GoogleGax.PollableOperation<DataAttributeBinding>
  {
    try await self.updateDataAttributeBinding(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func updateDataAttributeBinding(
    withPolling: UpdateDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataAttributeBinding>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func updateDataAttributeBinding(
    dataAttributeBinding: DataAttributeBinding?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<DataAttributeBinding> {
    let request = UpdateDataAttributeBindingRequest().with {
      $0.dataAttributeBinding = dataAttributeBinding
      $0.updateMask = updateMask
    }
    return try await self.updateDataAttributeBinding(withPolling: request)
  }

  @available(*, deprecated)
  public func deleteDataAttributeBinding(request: DeleteDataAttributeBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteDataAttributeBinding(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteDataAttributeBinding(
    request: DeleteDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteDataAttributeBinding(withPolling: DeleteDataAttributeBindingRequest)
    async throws -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteDataAttributeBinding(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func deleteDataAttributeBinding(
    withPolling: DeleteDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func deleteDataAttributeBinding(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteDataAttributeBindingRequest().with {
      $0.name = name
    }
    return try await self.deleteDataAttributeBinding(withPolling: request)
  }

  @available(*, deprecated)
  public func listDataAttributeBindings(request: ListDataAttributeBindingsRequest) async throws
    -> GoogleCloudDataplexV1.ListDataAttributeBindingsResponse
  {
    try await self.listDataAttributeBindings(request: request, options: .init())
  }

  @available(*, deprecated)
  public func listDataAttributeBindings(
    request: ListDataAttributeBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.ListDataAttributeBindingsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func listDataAttributeBindings(
    byItem: ListDataAttributeBindingsRequest
  ) throws -> any AsyncSequence<DataAttributeBinding, Swift.Error> {
    try self.listDataAttributeBindings(byItem: byItem, options: .init())
  }

  @available(*, deprecated)
  public func listDataAttributeBindings(
    byItem: ListDataAttributeBindingsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<DataAttributeBinding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDataplexV1.ListDataAttributeBindingsResponse
      in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  @available(*, deprecated)
  public func listDataAttributeBindings(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DataAttributeBinding, Swift.Error> {
    let request = ListDataAttributeBindingsRequest().with {
      $0.parent = parent
    }
    return try self.listDataAttributeBindings(byItem: request)
  }

  @available(*, deprecated)
  public func getDataAttributeBinding(request: GetDataAttributeBindingRequest) async throws
    -> GoogleCloudDataplexV1.DataAttributeBinding
  {
    try await self.getDataAttributeBinding(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getDataAttributeBinding(
    request: GetDataAttributeBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.DataAttributeBinding {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getDataAttributeBinding(
    name: Swift.String,
  ) async throws -> GoogleCloudDataplexV1.DataAttributeBinding {
    let request = GetDataAttributeBindingRequest().with {
      $0.name = name
    }
    return try await self.getDataAttributeBinding(request: request)
  }

  @available(*, deprecated)
  public func createDataAttribute(request: CreateDataAttributeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createDataAttribute(request: request, options: .init())
  }

  @available(*, deprecated)
  public func createDataAttribute(
    request: CreateDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func createDataAttribute(withPolling: CreateDataAttributeRequest) async throws
    -> any GoogleGax.PollableOperation<DataAttribute>
  {
    try await self.createDataAttribute(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func createDataAttribute(
    withPolling: CreateDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataAttribute> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataAttribute>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func createDataAttribute(
    parent: Swift.String,
    dataAttribute: DataAttribute?,
    dataAttributeId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<DataAttribute> {
    let request = CreateDataAttributeRequest().with {
      $0.parent = parent
      $0.dataAttribute = dataAttribute
      $0.dataAttributeId = dataAttributeId
    }
    return try await self.createDataAttribute(withPolling: request)
  }

  @available(*, deprecated)
  public func updateDataAttribute(request: UpdateDataAttributeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateDataAttribute(request: request, options: .init())
  }

  @available(*, deprecated)
  public func updateDataAttribute(
    request: UpdateDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func updateDataAttribute(withPolling: UpdateDataAttributeRequest) async throws
    -> any GoogleGax.PollableOperation<DataAttribute>
  {
    try await self.updateDataAttribute(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func updateDataAttribute(
    withPolling: UpdateDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<DataAttribute> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<DataAttribute>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func updateDataAttribute(
    dataAttribute: DataAttribute?,
    updateMask: GoogleWKT.FieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<DataAttribute> {
    let request = UpdateDataAttributeRequest().with {
      $0.dataAttribute = dataAttribute
      $0.updateMask = updateMask
    }
    return try await self.updateDataAttribute(withPolling: request)
  }

  @available(*, deprecated)
  public func deleteDataAttribute(request: DeleteDataAttributeRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteDataAttribute(request: request, options: .init())
  }

  @available(*, deprecated)
  public func deleteDataAttribute(
    request: DeleteDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func deleteDataAttribute(withPolling: DeleteDataAttributeRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteDataAttribute(withPolling: withPolling, options: .init())
  }

  @available(*, deprecated)
  public func deleteDataAttribute(
    withPolling: DeleteDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  @available(*, deprecated)
  public func deleteDataAttribute(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteDataAttributeRequest().with {
      $0.name = name
    }
    return try await self.deleteDataAttribute(withPolling: request)
  }

  @available(*, deprecated)
  public func listDataAttributes(request: ListDataAttributesRequest) async throws
    -> GoogleCloudDataplexV1.ListDataAttributesResponse
  {
    try await self.listDataAttributes(request: request, options: .init())
  }

  @available(*, deprecated)
  public func listDataAttributes(
    request: ListDataAttributesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.ListDataAttributesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func listDataAttributes(
    byItem: ListDataAttributesRequest
  ) throws -> any AsyncSequence<DataAttribute, Swift.Error> {
    try self.listDataAttributes(byItem: byItem, options: .init())
  }

  @available(*, deprecated)
  public func listDataAttributes(
    byItem: ListDataAttributesRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<DataAttribute, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDataplexV1.ListDataAttributesResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  @available(*, deprecated)
  public func listDataAttributes(
    parent: Swift.String,
  ) throws -> any AsyncSequence<DataAttribute, Swift.Error> {
    let request = ListDataAttributesRequest().with {
      $0.parent = parent
    }
    return try self.listDataAttributes(byItem: request)
  }

  @available(*, deprecated)
  public func getDataAttribute(request: GetDataAttributeRequest) async throws
    -> GoogleCloudDataplexV1.DataAttribute
  {
    try await self.getDataAttribute(request: request, options: .init())
  }

  @available(*, deprecated)
  public func getDataAttribute(
    request: GetDataAttributeRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudDataplexV1.DataAttribute {
    throw GoogleGax.RequestError.unimplemented
  }

  @available(*, deprecated)
  public func getDataAttribute(
    name: Swift.String,
  ) async throws -> GoogleCloudDataplexV1.DataAttribute {
    let request = GetDataAttributeRequest().with {
      $0.name = name
    }
    return try await self.getDataAttribute(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: GoogleIAMV1.SetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GoogleIAMV1.GetIamPolicyRequest) async throws
    -> GoogleIAMV1.Policy
  {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.Policy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: GoogleIAMV1.TestIamPermissionsRequest) async throws
    -> GoogleIAMV1.TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
