// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DataProfileScan related setting.
public struct DataProfileSpec: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. The percentage of the records to be selected from the dataset for
  /// DataScan.
  ///
  /// * Value can range between 0.0 and 100.0 with up to 3 significant decimal
  /// digits.
  /// * Sampling is not applied if `sampling_percent` is not specified, 0 or
  /// 100.
  public var samplingPercent: Swift.Float = Swift.Float()

  /// Optional. A filter applied to all rows in a single DataScan job.
  /// The filter needs to be a valid SQL expression for a WHERE clause in
  /// BigQuery standard SQL syntax.
  /// Example: col1 >= 0 AND col2 < 10
  public var rowFilter: Swift.String = Swift.String()

  /// Optional. Actions to take upon job completion..
  public var postScanActions: DataProfileSpec.PostScanActions? = nil

  /// Optional. The fields to include in data profile.
  ///
  /// If not specified, all fields at the time of profile scan job execution are
  /// included, except for ones listed in `exclude_fields`.
  public var includeFields: DataProfileSpec.SelectedFields? = nil

  /// Optional. The fields to exclude from data profile.
  ///
  /// If specified, the fields will be excluded from data profile, regardless of
  /// `include_fields` value.
  public var excludeFields: DataProfileSpec.SelectedFields? = nil

  /// Optional. If set, the latest DataScan job result will be published as
  /// Dataplex Universal Catalog metadata.
  public var catalogPublishingEnabled: Swift.Bool = Swift.Bool()

  /// Optional. The execution mode for the profile scan.
  public var mode: DataProfileSpec.Mode = DataProfileSpec.Mode()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataProfileSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataProfileSpec().with { $0.samplingPercent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let samplingPercent = CodingKeys(stringValue: "samplingPercent")
    static let rowFilter = CodingKeys(stringValue: "rowFilter")
    static let postScanActions = CodingKeys(stringValue: "postScanActions")
    static let includeFields = CodingKeys(stringValue: "includeFields")
    static let excludeFields = CodingKeys(stringValue: "excludeFields")
    static let catalogPublishingEnabled = CodingKeys(stringValue: "catalogPublishingEnabled")
    static let mode = CodingKeys(stringValue: "mode")

    static let _knownKeys: Set<Swift.String> = [
      "samplingPercent",
      "rowFilter",
      "postScanActions",
      "includeFields",
      "excludeFields",
      "catalogPublishingEnabled",
      "mode",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .samplingPercent) {
      self.samplingPercent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rowFilter) {
      self.rowFilter = value
    }
    self.postScanActions = try container.decodeIfPresent(
      DataProfileSpec.PostScanActions.self, forKey: .postScanActions)
    self.includeFields = try container.decodeIfPresent(
      DataProfileSpec.SelectedFields.self, forKey: .includeFields)
    self.excludeFields = try container.decodeIfPresent(
      DataProfileSpec.SelectedFields.self, forKey: .excludeFields)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .catalogPublishingEnabled)
    {
      self.catalogPublishingEnabled = value
    }
    if let value = try container.decodeIfPresent(DataProfileSpec.Mode.self, forKey: .mode) {
      self.mode = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.samplingPercent, forKey: .samplingPercent)
    try container.encode(self.rowFilter, forKey: .rowFilter)
    try container.encodeIfPresent(self.postScanActions, forKey: .postScanActions)
    try container.encodeIfPresent(self.includeFields, forKey: .includeFields)
    try container.encodeIfPresent(self.excludeFields, forKey: .excludeFields)
    try container.encode(self.catalogPublishingEnabled, forKey: .catalogPublishingEnabled)
    try container.encode(self.mode, forKey: .mode)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The configuration of post scan actions of DataProfileScan job.
  public struct PostScanActions: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. If set, results will be exported to the provided BigQuery
    /// table.
    public var bigqueryExport: DataProfileSpec.PostScanActions.BigQueryExport? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `PostScanActions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PostScanActions().with { $0.bigqueryExport = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let bigqueryExport = CodingKeys(stringValue: "bigqueryExport")

      static let _knownKeys: Set<Swift.String> = [
        "bigqueryExport"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.bigqueryExport = try container.decodeIfPresent(
        DataProfileSpec.PostScanActions.BigQueryExport.self, forKey: .bigqueryExport)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.bigqueryExport, forKey: .bigqueryExport)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The configuration of BigQuery export post scan action.
    public struct BigQueryExport: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Optional. The BigQuery table to export DataProfileScan results to.
      /// Format:
      /// //bigquery.googleapis.com/projects/PROJECT_ID/datasets/DATASET_ID/tables/TABLE_ID
      public var resultsTable: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `BigQueryExport`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = BigQueryExport().with { $0.resultsTable = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let resultsTable = CodingKeys(stringValue: "resultsTable")

        static let _knownKeys: Set<Swift.String> = [
          "resultsTable"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resultsTable) {
          self.resultsTable = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.resultsTable, forKey: .resultsTable)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataplex.v1.DataProfileSpec.PostScanActions.BigQueryExport"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.DataProfileSpec.PostScanActions"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The specification for fields to include or exclude in data profile scan.
  public struct SelectedFields: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Expected input is a list of fully qualified names of fields as
    /// in the schema.
    ///
    /// Only top-level field names for nested fields are supported.
    /// For instance, if 'x' is of nested field type, listing 'x' is supported
    /// but 'x.y.z' is not supported. Here 'y' and 'y.z' are nested fields of
    /// 'x'.
    public var fieldNames: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SelectedFields`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SelectedFields().with { $0.fieldNames = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let fieldNames = CodingKeys(stringValue: "fieldNames")

      static let _knownKeys: Set<Swift.String> = [
        "fieldNames"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .fieldNames) {
        self.fieldNames = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.fieldNames, forKey: .fieldNames)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.DataProfileSpec.SelectedFields"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Defines the execution mode for the profile scan.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Mode: Codable, Equatable, Sendable {
    /// Default value. This value is unused.
    case unspecified
    /// Performs standard profiling. The behavior is controlled by other fields
    /// such as `sampling_percent`, `row_filter`, and column filters.
    /// This mode allows for full scans or custom sampling.
    case standard
    /// Specifies lightweight profiling mode. This mode is optimized for
    /// low-latency, low-fidelity profiling.
    ///
    /// When this mode is selected, the following fields must not be set:
    /// `sampling_percent`, `row_filter`, `include_fields`, and `exclude_fields`.
    case lightweight
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .standard: return 1
      case .lightweight: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "MODE_UNSPECIFIED"
      case .standard: return "STANDARD"
      case .lightweight: return "LIGHTWEIGHT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Mode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "MODE_UNSPECIFIED": self = .unspecified
      case "STANDARD": self = .standard
      case "LIGHTWEIGHT": self = .lightweight
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Mode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .standard
      case 2: self = .lightweight
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("MODE_UNSPECIFIED")
      case .standard: return try container.encode("STANDARD")
      case .lightweight: return try container.encode("LIGHTWEIGHT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.DataProfileSpec"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
