// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The output of a DataQualityScan.
public struct DataQualityResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Overall data quality result -- `true` if all rules passed.
  public var passed: Swift.Bool = Swift.Bool()

  /// Output only. The overall data quality score.
  ///
  /// The score ranges between [0, 100] (up to two decimal points).
  public var score: Swift.Float? = nil

  /// Output only. A list of results at the dimension level.
  ///
  /// A dimension will have a corresponding `DataQualityDimensionResult` if and
  /// only if there is at least one rule with the 'dimension' field set to it.
  public var dimensions: [DataQualityDimensionResult] = []

  /// Output only. A list of results at the column level.
  ///
  /// A column will have a corresponding `DataQualityColumnResult` if and only if
  /// there is at least one rule with the 'column' field set to it.
  public var columns: [DataQualityColumnResult] = []

  /// Output only. A list of all the rules in a job, and their results.
  public var rules: [DataQualityRuleResult] = []

  /// Output only. The count of rows processed.
  public var rowCount: Swift.Int64 = Swift.Int64()

  /// Output only. The data scanned for this result.
  public var scannedData: ScannedData? = nil

  /// Output only. The result of post scan actions.
  public var postScanActionsResult: DataQualityResult.PostScanActionsResult? = nil

  /// Output only. The status of publishing the data scan as Dataplex Universal
  /// Catalog metadata.
  public var catalogPublishingStatus: DataScanCatalogPublishingStatus? = nil

  /// Output only. The generated assets for anomaly detection.
  public var anomalyDetectionGeneratedAssets: DataQualityResult.AnomalyDetectionGeneratedAssets? =
    nil

  /// Initialize a new instance of `DataQualityResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataQualityResult().with { $0.passed = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The result of post scan actions of DataQualityScan job.
  public struct PostScanActionsResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The result of BigQuery export post scan action.
    public var bigqueryExportResult: DataQualityResult.PostScanActionsResult.BigQueryExportResult? =
      nil

    /// Initialize a new instance of `PostScanActionsResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PostScanActionsResult().with { $0.bigqueryExportResult = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The result of BigQuery export post scan action.
    public struct BigQueryExportResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Output only. Execution state for the BigQuery exporting.
      public var state: DataQualityResult.PostScanActionsResult.BigQueryExportResult.State =
        DataQualityResult.PostScanActionsResult.BigQueryExportResult.State()

      /// Output only. Additional information about the BigQuery exporting.
      public var message: Swift.String = Swift.String()

      /// Initialize a new instance of `BigQueryExportResult`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = BigQueryExportResult().with { $0.state = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Execution state for the exporting.
      public enum State: Codable, Equatable, Sendable {
        /// The exporting state is unspecified.
        case unspecified
        /// The exporting completed successfully.
        case succeeded
        /// The exporting is no longer running due to an error.
        case failed
        /// The exporting is skipped due to no valid scan result to export
        /// (usually caused by scan failed).
        case skipped
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .succeeded: return 1
          case .failed: return 2
          case .skipped: return 3
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "STATE_UNSPECIFIED"
          case .succeeded: return "SUCCEEDED"
          case .failed: return "FAILED"
          case .skipped: return "SKIPPED"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "STATE_UNSPECIFIED": self = .unspecified
          case "SUCCEEDED": self = .succeeded
          case "FAILED": self = .failed
          case "SKIPPED": self = .skipped
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .succeeded
          case 2: self = .failed
          case 3: self = .skipped
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .succeeded: return try container.encode(1)
          case .failed: return try container.encode(2)
          case .skipped: return try container.encode(3)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataplex.v1.DataQualityResult.PostScanActionsResult.BigQueryExportResult"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.DataQualityResult.PostScanActionsResult"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The assets generated by Anomaly Detection Data Scan.
  public struct AnomalyDetectionGeneratedAssets: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The result table for anomaly detection.
    /// Format:
    /// PROJECT_ID.DATASET_ID.TABLE_ID
    /// If the result table is set at AnomalyDetectionAssets, the result table
    /// here would be the same as the one set in the
    /// AnomalyDetectionAssets.result_table.
    public var resultTable: Swift.String = Swift.String()

    /// Output only. The intermediate table for data anomaly detection.
    /// Format:
    /// PROJECT_ID.DATASET_ID.TABLE_ID
    public var dataIntermediateTable: Swift.String = Swift.String()

    /// Output only. The intermediate table for freshness anomaly detection.
    /// Format:
    /// PROJECT_ID.DATASET_ID.TABLE_ID
    public var freshnessIntermediateTable: Swift.String = Swift.String()

    /// Output only. The intermediate table for volume anomaly detection.
    /// Format:
    /// PROJECT_ID.DATASET_ID.TABLE_ID
    public var volumeIntermediateTable: Swift.String = Swift.String()

    /// Initialize a new instance of `AnomalyDetectionGeneratedAssets`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnomalyDetectionGeneratedAssets().with { $0.resultTable = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.dataplex.v1.DataQualityResult.AnomalyDetectionGeneratedAssets"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.DataQualityResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
