// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The output of a data discovery scan.
public struct DataDiscoveryResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Configuration for metadata publishing.
  public var bigqueryPublishing: DataDiscoveryResult.BigQueryPublishing? = nil

  /// Output only. Describes result statistics of a data scan discovery job.
  public var scanStatistics: DataDiscoveryResult.ScanStatistics? = nil

  /// Initialize a new instance of `DataDiscoveryResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataDiscoveryResult().with { $0.bigqueryPublishing = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Describes BigQuery publishing configurations.
  public struct BigQueryPublishing: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The BigQuery dataset the discovered tables are published to.
    public var dataset: Swift.String = Swift.String()

    /// Output only. The location of the BigQuery publishing dataset.
    public var location: Swift.String = Swift.String()

    /// Initialize a new instance of `BigQueryPublishing`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BigQueryPublishing().with { $0.dataset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.DataDiscoveryResult.BigQueryPublishing"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Describes result statistics of a data scan discovery job.
  public struct ScanStatistics: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The number of files scanned.
    public var scannedFileCount: Swift.Int32 = Swift.Int32()

    /// The data processed in bytes.
    public var dataProcessedBytes: Swift.Int64 = Swift.Int64()

    /// The number of files excluded.
    public var filesExcluded: Swift.Int32 = Swift.Int32()

    /// The number of tables created.
    public var tablesCreated: Swift.Int32 = Swift.Int32()

    /// The number of tables deleted.
    public var tablesDeleted: Swift.Int32 = Swift.Int32()

    /// The number of tables updated.
    public var tablesUpdated: Swift.Int32 = Swift.Int32()

    /// The number of filesets created.
    public var filesetsCreated: Swift.Int32 = Swift.Int32()

    /// The number of filesets deleted.
    public var filesetsDeleted: Swift.Int32 = Swift.Int32()

    /// The number of filesets updated.
    public var filesetsUpdated: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `ScanStatistics`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ScanStatistics().with { $0.scannedFileCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.DataDiscoveryResult.ScanStatistics"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.DataDiscoveryResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
