// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// DataQualityDimensionResult provides a more detailed, per-dimension view of
/// the results.
public struct DataQualityDimensionResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The dimension config specified in the DataQualitySpec, as is.
  public var dimension: DataQualityDimension? = nil

  /// Output only. Whether the dimension passed or failed.
  public var passed: Swift.Bool = Swift.Bool()

  /// Output only. The dimension-level data quality score for this data scan job
  /// if and only if the 'dimension' field is set.
  ///
  /// The score ranges between [0, 100] (up to two decimal
  /// points).
  public var score: Swift.Float? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DataQualityDimensionResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataQualityDimensionResult().with { $0.dimension = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let dimension = CodingKeys(stringValue: "dimension")
    static let passed = CodingKeys(stringValue: "passed")
    static let score = CodingKeys(stringValue: "score")

    static let _knownKeys: Set<Swift.String> = [
      "dimension",
      "passed",
      "score",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.dimension = try container.decodeIfPresent(DataQualityDimension.self, forKey: .dimension)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .passed) {
      self.passed = value
    }
    self.score = try container.decodeIfPresent(Swift.Float.self, forKey: .score)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.dimension, forKey: .dimension)
    try container.encode(self.passed, forKey: .passed)
    try container.encodeIfPresent(self.score, forKey: .score)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.DataQualityDimensionResult"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
