// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents tables and fileset metadata contained within a zone.
public struct Entity: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the entity, of the form:
  /// `projects/{project_number}/locations/{location_id}/lakes/{lake_id}/zones/{zone_id}/entities/{id}`.
  public var name: Swift.String = Swift.String()

  /// Optional. Display name must be shorter than or equal to 256 characters.
  public var displayName: Swift.String = Swift.String()

  /// Optional. User friendly longer description text. Must be shorter than or
  /// equal to 1024 characters.
  public var description: Swift.String = Swift.String()

  /// Output only. The time when the entity was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the entity was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Required. A user-provided entity ID. It is mutable, and will be used as the
  /// published table name. Specifying a new ID in an update entity
  /// request will override the existing value.
  /// The ID must contain only letters (a-z, A-Z), numbers (0-9), and
  /// underscores, and consist of 256 or fewer characters.
  public var id: Swift.String = Swift.String()

  /// Optional. The etag associated with the entity, which can be retrieved with
  /// a [GetEntity][] request. Required for update and delete requests.
  public var etag: Swift.String = Swift.String()

  /// Required. Immutable. The type of entity.
  public var type: Entity.Type_ = Entity.Type_()

  /// Required. Immutable. The ID of the asset associated with the storage
  /// location containing the entity data. The entity must be with in the same
  /// zone with the asset.
  public var asset: Swift.String = Swift.String()

  /// Required. Immutable. The storage path of the entity data.
  /// For Cloud Storage data, this is the fully-qualified path to the entity,
  /// such as `gs://bucket/path/to/data`. For BigQuery data, this is the name of
  /// the table resource, such as
  /// `projects/project_id/datasets/dataset_id/tables/table_id`.
  public var dataPath: Swift.String = Swift.String()

  /// Optional. The set of items within the data path constituting the data in
  /// the entity, represented as a glob path. Example:
  /// `gs://bucket/path/to/data/**/*.csv`.
  public var dataPathPattern: Swift.String = Swift.String()

  /// Output only. The name of the associated Data Catalog entry.
  public var catalogEntry: Swift.String = Swift.String()

  /// Required. Immutable. Identifies the storage system of the entity data.
  public var system: StorageSystem = StorageSystem()

  /// Required. Identifies the storage format of the entity data.
  /// It does not apply to entities with data stored in BigQuery.
  public var format: StorageFormat? = nil

  /// Output only. Metadata stores that the entity is compatible with.
  public var compatibility: Entity.CompatibilityStatus? = nil

  /// Output only. Identifies the access mechanism to the entity. Not user
  /// settable.
  public var access: StorageAccess? = nil

  /// Output only. System generated unique ID for the Entity. This ID will be
  /// different if the Entity is deleted and re-created with the same name.
  public var uid: Swift.String = Swift.String()

  /// Required. The description of the data structure and layout.
  /// The schema is not included in list responses. It is only included in
  /// `SCHEMA` and `FULL` entity views of a `GetEntity` response.
  public var schema: Schema? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Entity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Entity().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let id = CodingKeys(stringValue: "id")
    static let etag = CodingKeys(stringValue: "etag")
    static let type = CodingKeys(stringValue: "type")
    static let asset = CodingKeys(stringValue: "asset")
    static let dataPath = CodingKeys(stringValue: "dataPath")
    static let dataPathPattern = CodingKeys(stringValue: "dataPathPattern")
    static let catalogEntry = CodingKeys(stringValue: "catalogEntry")
    static let system = CodingKeys(stringValue: "system")
    static let format = CodingKeys(stringValue: "format")
    static let compatibility = CodingKeys(stringValue: "compatibility")
    static let access = CodingKeys(stringValue: "access")
    static let uid = CodingKeys(stringValue: "uid")
    static let schema = CodingKeys(stringValue: "schema")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "description",
      "createTime",
      "updateTime",
      "id",
      "etag",
      "type",
      "asset",
      "dataPath",
      "dataPathPattern",
      "catalogEntry",
      "system",
      "format",
      "compatibility",
      "access",
      "uid",
      "schema",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
      self.id = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Entity.Type_.self, forKey: .type) {
      self.type = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .asset) {
      self.asset = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataPath) {
      self.dataPath = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataPathPattern) {
      self.dataPathPattern = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .catalogEntry) {
      self.catalogEntry = value
    }
    if let value = try container.decodeIfPresent(StorageSystem.self, forKey: .system) {
      self.system = value
    }
    self.format = try container.decodeIfPresent(StorageFormat.self, forKey: .format)
    self.compatibility = try container.decodeIfPresent(
      Entity.CompatibilityStatus.self, forKey: .compatibility)
    self.access = try container.decodeIfPresent(StorageAccess.self, forKey: .access)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.schema = try container.decodeIfPresent(Schema.self, forKey: .schema)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.asset, forKey: .asset)
    try container.encode(self.dataPath, forKey: .dataPath)
    try container.encode(self.dataPathPattern, forKey: .dataPathPattern)
    try container.encode(self.catalogEntry, forKey: .catalogEntry)
    try container.encode(self.system, forKey: .system)
    try container.encodeIfPresent(self.format, forKey: .format)
    try container.encodeIfPresent(self.compatibility, forKey: .compatibility)
    try container.encodeIfPresent(self.access, forKey: .access)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.schema, forKey: .schema)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Provides compatibility information for various metadata stores.
  public struct CompatibilityStatus: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. Whether this entity is compatible with Hive Metastore.
    public var hiveMetastore: Entity.CompatibilityStatus.Compatibility? = nil

    /// Output only. Whether this entity is compatible with BigQuery.
    public var bigquery: Entity.CompatibilityStatus.Compatibility? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `CompatibilityStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CompatibilityStatus().with { $0.hiveMetastore = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let hiveMetastore = CodingKeys(stringValue: "hiveMetastore")
      static let bigquery = CodingKeys(stringValue: "bigquery")

      static let _knownKeys: Set<Swift.String> = [
        "hiveMetastore",
        "bigquery",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.hiveMetastore = try container.decodeIfPresent(
        Entity.CompatibilityStatus.Compatibility.self, forKey: .hiveMetastore)
      self.bigquery = try container.decodeIfPresent(
        Entity.CompatibilityStatus.Compatibility.self, forKey: .bigquery)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.hiveMetastore, forKey: .hiveMetastore)
      try container.encodeIfPresent(self.bigquery, forKey: .bigquery)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Provides compatibility information for a specific metadata store.
    public struct Compatibility: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Output only. Whether the entity is compatible and can be represented in
      /// the metadata store.
      public var compatible: Swift.Bool = Swift.Bool()

      /// Output only. Provides additional detail if the entity is incompatible
      /// with the metadata store.
      public var reason: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

      /// Initialize a new instance of `Compatibility`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Compatibility().with { $0.compatible = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let compatible = CodingKeys(stringValue: "compatible")
        static let reason = CodingKeys(stringValue: "reason")

        static let _knownKeys: Set<Swift.String> = [
          "compatible",
          "reason",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .compatible) {
          self.compatible = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reason) {
          self.reason = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleCloudWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.compatible, forKey: .compatible)
        try container.encode(self.reason, forKey: .reason)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataplex.v1.Entity.CompatibilityStatus.Compatibility"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.Entity.CompatibilityStatus"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of entity.
  public enum Type_: Codable, Equatable, Sendable {
    /// Type unspecified.
    case unspecified
    /// Structured and semi-structured data.
    case table
    /// Unstructured data.
    case fileset
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .table: return 1
      case .fileset: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .table: return "TABLE"
      case .fileset: return "FILESET"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "TABLE": self = .table
      case "FILESET": self = .fileset
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .table
      case 2: self = .fileset
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .table: return try container.encode("TABLE")
      case .fileset: return try container.encode("FILESET")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.Entity"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
