// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Entry Type is a template for creating Entries.
public struct EntryType: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The relative resource name of the EntryType, of the form:
  /// projects/{project_number}/locations/{location_id}/entryTypes/{entry_type_id}.
  public var name: Swift.String = Swift.String()

  /// Output only. System generated globally unique ID for the EntryType. This ID
  /// will be different if the EntryType is deleted and re-created with the same
  /// name.
  public var uid: Swift.String = Swift.String()

  /// Output only. The time when the EntryType was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time when the EntryType was last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Optional. Description of the EntryType.
  public var description: Swift.String = Swift.String()

  /// Optional. User friendly display name.
  public var displayName: Swift.String = Swift.String()

  /// Optional. User-defined labels for the EntryType.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. This checksum is computed by the service, and might be sent on
  /// update and delete requests to ensure the client has an up-to-date value
  /// before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Optional. Indicates the classes this Entry Type belongs to, for example,
  /// TABLE, DATABASE, MODEL.
  public var typeAliases: [Swift.String] = []

  /// Optional. The platform that Entries of this type belongs to.
  public var platform: Swift.String = Swift.String()

  /// Optional. The system that Entries of this type belongs to. Examples include
  /// CloudSQL, MariaDB etc
  public var system: Swift.String = Swift.String()

  /// AspectInfo for the entry type.
  public var requiredAspects: [EntryType.AspectInfo] = []

  /// Immutable. Authorization defined for this type.
  public var authorization: EntryType.Authorization? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EntryType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EntryType().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let description = CodingKeys(stringValue: "description")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let labels = CodingKeys(stringValue: "labels")
    static let etag = CodingKeys(stringValue: "etag")
    static let typeAliases = CodingKeys(stringValue: "typeAliases")
    static let platform = CodingKeys(stringValue: "platform")
    static let system = CodingKeys(stringValue: "system")
    static let requiredAspects = CodingKeys(stringValue: "requiredAspects")
    static let authorization = CodingKeys(stringValue: "authorization")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "createTime",
      "updateTime",
      "description",
      "displayName",
      "labels",
      "etag",
      "typeAliases",
      "platform",
      "system",
      "requiredAspects",
      "authorization",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .typeAliases) {
      self.typeAliases = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .platform) {
      self.platform = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .system) {
      self.system = value
    }
    if let value = try container.decodeIfPresent(
      [EntryType.AspectInfo].self, forKey: .requiredAspects)
    {
      self.requiredAspects = value
    }
    self.authorization = try container.decodeIfPresent(
      EntryType.Authorization.self, forKey: .authorization)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.typeAliases, forKey: .typeAliases)
    try container.encode(self.platform, forKey: .platform)
    try container.encode(self.system, forKey: .system)
    try container.encode(self.requiredAspects, forKey: .requiredAspects)
    try container.encodeIfPresent(self.authorization, forKey: .authorization)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public struct AspectInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required aspect type for the entry type.
    public var type: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AspectInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AspectInfo().with { $0.type = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let type = CodingKeys(stringValue: "type")

      static let _knownKeys: Set<Swift.String> = [
        "type"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.type, forKey: .type)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.EntryType.AspectInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Authorization for an Entry Type.
  public struct Authorization: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Immutable. The IAM permission grantable on the Entry Group to allow
    /// access to instantiate Entries of Dataplex Universal Catalog owned Entry
    /// Types, only settable for Dataplex Universal Catalog owned Types.
    public var alternateUsePermission: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Authorization`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Authorization().with { $0.alternateUsePermission = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let alternateUsePermission = CodingKeys(stringValue: "alternateUsePermission")

      static let _knownKeys: Set<Swift.String> = [
        "alternateUsePermission"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .alternateUsePermission)
      {
        self.alternateUsePermission = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.alternateUsePermission, forKey: .alternateUsePermission)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.EntryType.Authorization"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.EntryType"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
