// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A Glossary represents a collection of GlossaryCategories and GlossaryTerms
/// defined by the user. Glossary is a top level resource and is the Google Cloud
/// parent resource of all the GlossaryCategories and GlossaryTerms within it.
public struct Glossary: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource name of the Glossary.
  /// Format:
  /// projects/{project_id_or_number}/locations/{location_id}/glossaries/{glossary_id}
  public var name: Swift.String = Swift.String()

  /// Output only. System generated unique id for the Glossary. This ID will be
  /// different if the Glossary is deleted and re-created with the
  /// same name.
  public var uid: Swift.String = Swift.String()

  /// Optional. User friendly display name of the Glossary. This is user-mutable.
  /// This will be same as the GlossaryId, if not specified.
  public var displayName: Swift.String = Swift.String()

  /// Optional. The user-mutable description of the Glossary.
  public var description: Swift.String = Swift.String()

  /// Output only. The time at which the Glossary was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which the Glossary was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. User-defined labels for the Glossary.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. The number of GlossaryTerms in the Glossary.
  public var termCount: Swift.Int32 = Swift.Int32()

  /// Output only. The number of GlossaryCategories in the Glossary.
  public var categoryCount: Swift.Int32 = Swift.Int32()

  /// Optional. Needed for resource freshness validation.
  /// This checksum is computed by the server based on the value of other
  /// fields, and may be sent on update and delete requests to ensure the
  /// client has an up-to-date value before proceeding.
  public var etag: Swift.String = Swift.String()

  /// Initialize a new instance of `Glossary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Glossary().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.Glossary"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
