// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Payload associated with Governance related log events.
public struct GovernanceEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The log message.
  public var message: Swift.String = Swift.String()

  /// The type of the event.
  public var eventType: GovernanceEvent.EventType = GovernanceEvent.EventType()

  /// Entity resource information if the log event is associated with a
  /// specific entity.
  public var entity: GovernanceEvent.Entity? = nil

  /// Initialize a new instance of `GovernanceEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GovernanceEvent().with { $0.message = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Information about Entity resource that the log event is associated with.
  public struct Entity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The Entity resource the log event is associated with.
    /// Format:
    /// `projects/{project_number}/locations/{location_id}/lakes/{lake_id}/zones/{zone_id}/entities/{entity_id}`
    public var entity: Swift.String = Swift.String()

    /// Type of entity.
    public var entityType: GovernanceEvent.Entity.EntityType = GovernanceEvent.Entity.EntityType()

    /// Initialize a new instance of `Entity`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Entity().with { $0.entity = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Type of entity.
    public enum EntityType: Codable, Equatable, Sendable {
      /// An unspecified Entity type.
      case unspecified
      /// Table entity type.
      case table
      /// Fileset entity type.
      case fileset
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .table: return 1
        case .fileset: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ENTITY_TYPE_UNSPECIFIED"
        case .table: return "TABLE"
        case .fileset: return "FILESET"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EntityType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ENTITY_TYPE_UNSPECIFIED": self = .unspecified
        case "TABLE": self = .table
        case "FILESET": self = .fileset
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EntityType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .table
        case 2: self = .fileset
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .table: return try container.encode(1)
        case .fileset: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.GovernanceEvent.Entity"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Type of governance log event.
  public enum EventType: Codable, Equatable, Sendable {
    /// An unspecified event type.
    case unspecified
    /// Resource IAM policy update event.
    case resourceIamPolicyUpdate
    /// BigQuery table create event.
    case bigqueryTableCreate
    /// BigQuery table update event.
    case bigqueryTableUpdate
    /// BigQuery table delete event.
    case bigqueryTableDelete
    /// BigQuery connection create event.
    case bigqueryConnectionCreate
    /// BigQuery connection update event.
    case bigqueryConnectionUpdate
    /// BigQuery connection delete event.
    case bigqueryConnectionDelete
    /// BigQuery taxonomy created.
    case bigqueryTaxonomyCreate
    /// BigQuery policy tag created.
    case bigqueryPolicyTagCreate
    /// BigQuery policy tag deleted.
    case bigqueryPolicyTagDelete
    /// BigQuery set iam policy for policy tag.
    case bigqueryPolicyTagSetIamPolicy
    /// Access policy update event.
    case accessPolicyUpdate
    /// Number of resources matched with particular Query.
    case governanceRuleMatchedResources
    /// Rule processing exceeds the allowed limit.
    case governanceRuleSearchLimitExceeds
    /// Rule processing errors.
    case governanceRuleErrors
    /// Governance rule processing Event.
    case governanceRuleProcessing
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .resourceIamPolicyUpdate: return 1
      case .bigqueryTableCreate: return 2
      case .bigqueryTableUpdate: return 3
      case .bigqueryTableDelete: return 4
      case .bigqueryConnectionCreate: return 5
      case .bigqueryConnectionUpdate: return 6
      case .bigqueryConnectionDelete: return 7
      case .bigqueryTaxonomyCreate: return 10
      case .bigqueryPolicyTagCreate: return 11
      case .bigqueryPolicyTagDelete: return 12
      case .bigqueryPolicyTagSetIamPolicy: return 13
      case .accessPolicyUpdate: return 14
      case .governanceRuleMatchedResources: return 15
      case .governanceRuleSearchLimitExceeds: return 16
      case .governanceRuleErrors: return 17
      case .governanceRuleProcessing: return 18
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EVENT_TYPE_UNSPECIFIED"
      case .resourceIamPolicyUpdate: return "RESOURCE_IAM_POLICY_UPDATE"
      case .bigqueryTableCreate: return "BIGQUERY_TABLE_CREATE"
      case .bigqueryTableUpdate: return "BIGQUERY_TABLE_UPDATE"
      case .bigqueryTableDelete: return "BIGQUERY_TABLE_DELETE"
      case .bigqueryConnectionCreate: return "BIGQUERY_CONNECTION_CREATE"
      case .bigqueryConnectionUpdate: return "BIGQUERY_CONNECTION_UPDATE"
      case .bigqueryConnectionDelete: return "BIGQUERY_CONNECTION_DELETE"
      case .bigqueryTaxonomyCreate: return "BIGQUERY_TAXONOMY_CREATE"
      case .bigqueryPolicyTagCreate: return "BIGQUERY_POLICY_TAG_CREATE"
      case .bigqueryPolicyTagDelete: return "BIGQUERY_POLICY_TAG_DELETE"
      case .bigqueryPolicyTagSetIamPolicy: return "BIGQUERY_POLICY_TAG_SET_IAM_POLICY"
      case .accessPolicyUpdate: return "ACCESS_POLICY_UPDATE"
      case .governanceRuleMatchedResources: return "GOVERNANCE_RULE_MATCHED_RESOURCES"
      case .governanceRuleSearchLimitExceeds: return "GOVERNANCE_RULE_SEARCH_LIMIT_EXCEEDS"
      case .governanceRuleErrors: return "GOVERNANCE_RULE_ERRORS"
      case .governanceRuleProcessing: return "GOVERNANCE_RULE_PROCESSING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "RESOURCE_IAM_POLICY_UPDATE": self = .resourceIamPolicyUpdate
      case "BIGQUERY_TABLE_CREATE": self = .bigqueryTableCreate
      case "BIGQUERY_TABLE_UPDATE": self = .bigqueryTableUpdate
      case "BIGQUERY_TABLE_DELETE": self = .bigqueryTableDelete
      case "BIGQUERY_CONNECTION_CREATE": self = .bigqueryConnectionCreate
      case "BIGQUERY_CONNECTION_UPDATE": self = .bigqueryConnectionUpdate
      case "BIGQUERY_CONNECTION_DELETE": self = .bigqueryConnectionDelete
      case "BIGQUERY_TAXONOMY_CREATE": self = .bigqueryTaxonomyCreate
      case "BIGQUERY_POLICY_TAG_CREATE": self = .bigqueryPolicyTagCreate
      case "BIGQUERY_POLICY_TAG_DELETE": self = .bigqueryPolicyTagDelete
      case "BIGQUERY_POLICY_TAG_SET_IAM_POLICY": self = .bigqueryPolicyTagSetIamPolicy
      case "ACCESS_POLICY_UPDATE": self = .accessPolicyUpdate
      case "GOVERNANCE_RULE_MATCHED_RESOURCES": self = .governanceRuleMatchedResources
      case "GOVERNANCE_RULE_SEARCH_LIMIT_EXCEEDS": self = .governanceRuleSearchLimitExceeds
      case "GOVERNANCE_RULE_ERRORS": self = .governanceRuleErrors
      case "GOVERNANCE_RULE_PROCESSING": self = .governanceRuleProcessing
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .resourceIamPolicyUpdate
      case 2: self = .bigqueryTableCreate
      case 3: self = .bigqueryTableUpdate
      case 4: self = .bigqueryTableDelete
      case 5: self = .bigqueryConnectionCreate
      case 6: self = .bigqueryConnectionUpdate
      case 7: self = .bigqueryConnectionDelete
      case 10: self = .bigqueryTaxonomyCreate
      case 11: self = .bigqueryPolicyTagCreate
      case 12: self = .bigqueryPolicyTagDelete
      case 13: self = .bigqueryPolicyTagSetIamPolicy
      case 14: self = .accessPolicyUpdate
      case 15: self = .governanceRuleMatchedResources
      case 16: self = .governanceRuleSearchLimitExceeds
      case 17: self = .governanceRuleErrors
      case 18: self = .governanceRuleProcessing
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .resourceIamPolicyUpdate: return try container.encode(1)
      case .bigqueryTableCreate: return try container.encode(2)
      case .bigqueryTableUpdate: return try container.encode(3)
      case .bigqueryTableDelete: return try container.encode(4)
      case .bigqueryConnectionCreate: return try container.encode(5)
      case .bigqueryConnectionUpdate: return try container.encode(6)
      case .bigqueryConnectionDelete: return try container.encode(7)
      case .bigqueryTaxonomyCreate: return try container.encode(10)
      case .bigqueryPolicyTagCreate: return try container.encode(11)
      case .bigqueryPolicyTagDelete: return try container.encode(12)
      case .bigqueryPolicyTagSetIamPolicy: return try container.encode(13)
      case .accessPolicyUpdate: return try container.encode(14)
      case .governanceRuleMatchedResources: return try container.encode(15)
      case .governanceRuleSearchLimitExceeds: return try container.encode(16)
      case .governanceRuleErrors: return try container.encode(17)
      case .governanceRuleProcessing: return try container.encode(18)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.GovernanceEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
