// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An object that describes the values that you want to set for an entry and its
/// attached aspects when you import metadata. Used when you run a metadata
/// import job. See
/// [CreateMetadataJob][google.cloud.dataplex.v1.CatalogService.CreateMetadataJob].
///
/// You provide a collection of import items in a metadata import file. For more
/// information about how to create a metadata import file, see [Metadata import
/// file](https://cloud.google.com/dataplex/docs/import-metadata#metadata-import-file).
///
/// [google.cloud.dataplex.v1.CatalogService.CreateMetadataJob]: <doc:CatalogServiceClient/createMetadataJob(request:options:)>
public struct ImportItem: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Information about an entry and its attached aspects.
  public var entry: Entry? = nil

  /// Information about the entry link. User should provide either one of the
  /// entry or entry_link. While providing entry_link, user should not
  /// provide update_mask and aspect_keys.
  public var entryLink: EntryLink? = nil

  /// The fields to update, in paths that are relative to the `Entry` resource.
  /// Separate each field with a comma.
  ///
  /// In `FULL` entry sync mode, Dataplex Universal Catalog includes the paths of
  /// all of the fields for an entry that can be modified, including aspects.
  /// This means that Dataplex Universal Catalog replaces the existing entry with
  /// the entry in the metadata import file. All modifiable fields are updated,
  /// regardless of the fields that are listed in the update mask, and regardless
  /// of whether a field is present in the `entry` object.
  ///
  /// The `update_mask` field is ignored when an entry is created or re-created.
  ///
  /// In an aspect-only metadata job (when entry sync mode is `NONE`), set this
  /// value to `aspects`.
  ///
  ///
  /// Dataplex Universal Catalog also determines which entries and aspects to
  /// modify by comparing the values and timestamps that you provide in the
  /// metadata import file with the values and timestamps that exist in your
  /// project. For more information, see [Comparison
  /// logic](https://cloud.google.com/dataplex/docs/import-metadata#data-modification-logic).
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// The aspects to modify. Supports the following syntaxes:
  ///
  /// * `{aspect_type_reference}`: matches aspects that belong to the specified
  /// aspect type and are attached directly to the entry.
  /// * `{aspect_type_reference}@{path}`: matches aspects that belong to the
  /// specified aspect type and path.
  /// * `{aspect_type_reference}@*` : matches aspects of the given type for all
  /// paths.
  /// * `*@path` : matches aspects of all types on the given path.
  ///
  /// Replace `{aspect_type_reference}` with a reference to the aspect type, in
  /// the format
  /// `{project_id_or_number}.{location_id}.{aspect_type_id}`.
  ///
  /// In `FULL` entry sync mode, if you leave this field empty, it is treated as
  /// specifying exactly those aspects that are present within the specified
  /// entry. Dataplex Universal Catalog implicitly adds the keys for all of the
  /// required aspects of an entry.
  public var aspectKeys: [Swift.String] = []

  /// Initialize a new instance of `ImportItem`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImportItem().with { $0.entry = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.ImportItem"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
