// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// List Entries request.
public struct ListEntriesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the parent Entry Group:
  /// `projects/{project}/locations/{location}/entryGroups/{entry_group}`.
  public var parent: Swift.String = Swift.String()

  /// Optional. Number of items to return per page. If there are remaining
  /// results, the service returns a next_page_token. If unspecified, the service
  /// returns at most 10 Entries. The maximum value is 100; values above 100 will
  /// be coerced to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Page token received from a previous `ListEntries` call. Provide
  /// this to retrieve the subsequent page.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A filter on the entries to return. Filters are case-sensitive.
  /// You can filter the request by the following fields:
  ///
  /// * entry_type
  /// * entry_source.display_name
  /// * parent_entry
  ///
  /// The comparison operators are =, !=, <, >, <=, >=. The service compares
  /// strings according to lexical order.
  ///
  /// You can use the logical operators AND, OR, NOT in the filter.
  ///
  /// You can use Wildcard "*", but for entry_type and parent_entry you need to
  /// provide the full project id or number.
  ///
  /// You cannot use parent_entry in conjunction with other fields.
  ///
  /// Example filter expressions:
  ///
  /// * "entry_source.display_name=AnExampleDisplayName"
  /// * "entry_type=projects/example-project/locations/global/entryTypes/example-entry_type"
  /// * "entry_type=projects/example-project/locations/us/entryTypes/a* OR
  /// entry_type=projects/another-project/locations/*"
  /// * "NOT entry_source.display_name=AnotherExampleDisplayName"
  /// * "parent_entry=projects/example-project/locations/us/entryGroups/example-entry-group/entries/example-entry"
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListEntriesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListEntriesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.ListEntriesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
