// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleGax
@_spi(GoogleCloudInternal) public import GoogleWKT

/// List Glossaries Response
public struct ListGlossariesResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Lists the Glossaries in the specified parent.
  public var glossaries: [Glossary] = []

  /// A token, which can be sent as `page_token` to retrieve the next page.
  /// If this field is omitted, there are no subsequent pages.
  public var nextPageToken: Swift.String = Swift.String()

  /// Locations that the service couldn't reach.
  public var unreachableLocations: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListGlossariesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListGlossariesResponse().with { $0.glossaries = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let glossaries = CodingKeys(stringValue: "glossaries")
    static let nextPageToken = CodingKeys(stringValue: "nextPageToken")
    static let unreachableLocations = CodingKeys(stringValue: "unreachableLocations")

    static let _knownKeys: Set<Swift.String> = [
      "glossaries",
      "nextPageToken",
      "unreachableLocations",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Glossary].self, forKey: .glossaries) {
      self.glossaries = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
      self.nextPageToken = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .unreachableLocations)
    {
      self.unreachableLocations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.glossaries, forKey: .glossaries)
    try container.encode(self.nextPageToken, forKey: .nextPageToken)
    try container.encode(self.unreachableLocations, forKey: .unreachableLocations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.ListGlossariesResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}

@_spi(GoogleCloudInternal)
extension ListGlossariesResponse: GoogleGax._PaginatedResponse {
  public func _getPaginatedItems() -> [Glossary] {
    return self.glossaries
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
