// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A metadata job resource.
public struct MetadataJob: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The name of the resource that the configuration is
  /// applied to, in the format
  /// `projects/{project_number}/locations/{location_id}/metadataJobs/{metadata_job_id}`.
  public var name: Swift.String = Swift.String()

  /// Output only. A system-generated, globally unique ID for the metadata job.
  /// If the metadata job is deleted and then re-created with the same name, this
  /// ID is different.
  public var uid: Swift.String = Swift.String()

  /// Output only. The time when the metadata job was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the metadata job was updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. User-defined labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Metadata job type.
  public var type: MetadataJob.Type_ = MetadataJob.Type_()

  /// Output only. Metadata job status.
  public var status: MetadataJob.Status? = nil

  public var spec: OneOf_Spec? = nil

  public var result: OneOf_Result? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MetadataJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MetadataJob().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let type = CodingKeys(stringValue: "type")
    static let importSpec = CodingKeys(stringValue: "importSpec")
    static let exportSpec = CodingKeys(stringValue: "exportSpec")
    static let importResult = CodingKeys(stringValue: "importResult")
    static let exportResult = CodingKeys(stringValue: "exportResult")
    static let status = CodingKeys(stringValue: "status")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "createTime",
      "updateTime",
      "labels",
      "type",
      "importSpec",
      "exportSpec",
      "importResult",
      "exportResult",
      "status",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(MetadataJob.Type_.self, forKey: .type) {
      self.type = value
    }
    self.status = try container.decodeIfPresent(MetadataJob.Status.self, forKey: .status)

    var spec: OneOf_Spec? = nil
    let specCheckAndSet = {
      if spec != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'spec'"
          ))
      }
      spec = $0
    }
    if let importSpec = try container.decodeIfPresent(
      MetadataJob.ImportJobSpec?.self, forKey: .importSpec)
    {
      try specCheckAndSet(.importSpec(importSpec))
    }
    if let exportSpec = try container.decodeIfPresent(
      MetadataJob.ExportJobSpec?.self, forKey: .exportSpec)
    {
      try specCheckAndSet(.exportSpec(exportSpec))
    }
    self.spec = spec

    var result: OneOf_Result? = nil
    let resultCheckAndSet = {
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = $0
    }
    if let importResult = try container.decodeIfPresent(
      MetadataJob.ImportJobResult?.self, forKey: .importResult)
    {
      try resultCheckAndSet(.importResult(importResult))
    }
    if let exportResult = try container.decodeIfPresent(
      MetadataJob.ExportJobResult?.self, forKey: .exportResult)
    {
      try resultCheckAndSet(.exportResult(exportResult))
    }
    self.result = result
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.type, forKey: .type)
    try container.encodeIfPresent(self.status, forKey: .status)

    if let choice = self.spec {
      switch choice {
      case .importSpec(let value):
        try container.encode(value, forKey: .importSpec)
      case .exportSpec(let value):
        try container.encode(value, forKey: .exportSpec)
      }
    }

    if let choice = self.result {
      switch choice {
      case .importResult(let value):
        try container.encode(value, forKey: .importResult)
      case .exportResult(let value):
        try container.encode(value, forKey: .exportResult)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Results from a metadata import job.
  public struct ImportJobResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The total number of entries that were deleted.
    public var deletedEntries: Swift.Int64 = Swift.Int64()

    /// Output only. The total number of entries that were updated.
    public var updatedEntries: Swift.Int64 = Swift.Int64()

    /// Output only. The total number of entries that were created.
    public var createdEntries: Swift.Int64 = Swift.Int64()

    /// Output only. The total number of entries that were unchanged.
    public var unchangedEntries: Swift.Int64 = Swift.Int64()

    /// Output only. The total number of entries that were recreated.
    public var recreatedEntries: Swift.Int64 = Swift.Int64()

    /// Output only. The time when the status was updated.
    public var updateTime: GoogleWKT.WKTTimestamp? = nil

    /// Output only. The total number of entry links that were successfully
    /// deleted.
    public var deletedEntryLinks: Swift.Int64 = Swift.Int64()

    /// Output only. The total number of entry links that were successfully
    /// created.
    public var createdEntryLinks: Swift.Int64 = Swift.Int64()

    /// Output only. The total number of entry links that were left unchanged.
    public var unchangedEntryLinks: Swift.Int64 = Swift.Int64()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ImportJobResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportJobResult().with { $0.deletedEntries = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let deletedEntries = CodingKeys(stringValue: "deletedEntries")
      static let updatedEntries = CodingKeys(stringValue: "updatedEntries")
      static let createdEntries = CodingKeys(stringValue: "createdEntries")
      static let unchangedEntries = CodingKeys(stringValue: "unchangedEntries")
      static let recreatedEntries = CodingKeys(stringValue: "recreatedEntries")
      static let updateTime = CodingKeys(stringValue: "updateTime")
      static let deletedEntryLinks = CodingKeys(stringValue: "deletedEntryLinks")
      static let createdEntryLinks = CodingKeys(stringValue: "createdEntryLinks")
      static let unchangedEntryLinks = CodingKeys(stringValue: "unchangedEntryLinks")

      static let _knownKeys: Set<Swift.String> = [
        "deletedEntries",
        "updatedEntries",
        "createdEntries",
        "unchangedEntries",
        "recreatedEntries",
        "updateTime",
        "deletedEntryLinks",
        "createdEntryLinks",
        "unchangedEntryLinks",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .deletedEntries) {
        self.deletedEntries = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .updatedEntries) {
        self.updatedEntries = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .createdEntries) {
        self.createdEntries = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .unchangedEntries) {
        self.unchangedEntries = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .recreatedEntries) {
        self.recreatedEntries = value
      }
      self.updateTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .deletedEntryLinks) {
        self.deletedEntryLinks = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .createdEntryLinks) {
        self.createdEntryLinks = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .unchangedEntryLinks) {
        self.unchangedEntryLinks = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.deletedEntries, forKey: .deletedEntries)
      try container.encode(self.updatedEntries, forKey: .updatedEntries)
      try container.encode(self.createdEntries, forKey: .createdEntries)
      try container.encode(self.unchangedEntries, forKey: .unchangedEntries)
      try container.encode(self.recreatedEntries, forKey: .recreatedEntries)
      try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
      try container.encode(self.deletedEntryLinks, forKey: .deletedEntryLinks)
      try container.encode(self.createdEntryLinks, forKey: .createdEntryLinks)
      try container.encode(self.unchangedEntryLinks, forKey: .unchangedEntryLinks)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.MetadataJob.ImportJobResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Summary results from a metadata export job. The results are a snapshot of
  /// the metadata at the time when the job was created. The exported entries are
  /// saved to a Cloud Storage bucket.
  public struct ExportJobResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The number of entries that were exported.
    public var exportedEntries: Swift.Int64 = Swift.Int64()

    /// Output only. The error message if the metadata export job failed.
    public var errorMessage: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ExportJobResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExportJobResult().with { $0.exportedEntries = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let exportedEntries = CodingKeys(stringValue: "exportedEntries")
      static let errorMessage = CodingKeys(stringValue: "errorMessage")

      static let _knownKeys: Set<Swift.String> = [
        "exportedEntries",
        "errorMessage",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .exportedEntries) {
        self.exportedEntries = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .errorMessage) {
        self.errorMessage = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.exportedEntries, forKey: .exportedEntries)
      try container.encode(self.errorMessage, forKey: .errorMessage)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.MetadataJob.ExportJobResult"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Job specification for a metadata import job.
  ///
  /// You can run the following kinds of metadata import jobs:
  ///
  /// * Full sync of entries with incremental import of their aspects.
  /// Supported for custom entries.
  /// * Incremental import of aspects only. Supported for aspects that belong
  /// to custom entries and system entries. For custom entries, you can modify
  /// both optional aspects and required aspects. For system entries, you can
  /// modify optional aspects.
  public struct ImportJobSpec: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The URI of a Cloud Storage bucket or folder (beginning with
    /// `gs://` and ending with `/`) that contains the metadata import files for
    /// this job.
    ///
    /// A metadata import file defines the values to set for each of the entries
    /// and aspects in a metadata import job. For more information about how to
    /// create a metadata import file and the file requirements, see [Metadata
    /// import
    /// file](https://cloud.google.com/dataplex/docs/import-metadata#metadata-import-file).
    ///
    /// You can provide multiple metadata import files in the same metadata job.
    /// The bucket or folder must contain at least one metadata import file, in
    /// JSON Lines format (either `.json` or `.jsonl` file extension).
    ///
    /// In `FULL` entry sync mode, don't save the metadata import file in a
    /// folder named `SOURCE_STORAGE_URI/deletions/`.
    ///
    /// **Caution**: If the metadata import file contains no data, all entries
    /// and aspects that belong to the job's scope are deleted.
    public var sourceStorageUri: Swift.String = Swift.String()

    /// Optional. The time when the process that created the metadata import
    /// files began.
    public var sourceCreateTime: GoogleWKT.WKTTimestamp? = nil

    /// Required. A boundary on the scope of impact that the metadata import job
    /// can have.
    public var scope: MetadataJob.ImportJobSpec.ImportJobScope? = nil

    /// Required. The sync mode for entries.
    public var entrySyncMode: MetadataJob.ImportJobSpec.SyncMode = MetadataJob.ImportJobSpec
      .SyncMode()

    /// Required. The sync mode for aspects.
    public var aspectSyncMode: MetadataJob.ImportJobSpec.SyncMode = MetadataJob.ImportJobSpec
      .SyncMode()

    /// Optional. The level of logs to write to Cloud Logging for this job.
    ///
    /// Debug-level logs provide highly-detailed information for
    /// troubleshooting, but their increased verbosity could incur [additional
    /// costs](https://cloud.google.com/stackdriver/pricing) that might not be
    /// merited for all jobs.
    ///
    /// If unspecified, defaults to `INFO`.
    public var logLevel: MetadataJob.ImportJobSpec.LogLevel = MetadataJob.ImportJobSpec.LogLevel()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ImportJobSpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportJobSpec().with { $0.sourceStorageUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sourceStorageUri = CodingKeys(stringValue: "sourceStorageUri")
      static let sourceCreateTime = CodingKeys(stringValue: "sourceCreateTime")
      static let scope = CodingKeys(stringValue: "scope")
      static let entrySyncMode = CodingKeys(stringValue: "entrySyncMode")
      static let aspectSyncMode = CodingKeys(stringValue: "aspectSyncMode")
      static let logLevel = CodingKeys(stringValue: "logLevel")

      static let _knownKeys: Set<Swift.String> = [
        "sourceStorageUri",
        "sourceCreateTime",
        "scope",
        "entrySyncMode",
        "aspectSyncMode",
        "logLevel",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceStorageUri) {
        self.sourceStorageUri = value
      }
      self.sourceCreateTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .sourceCreateTime)
      self.scope = try container.decodeIfPresent(
        MetadataJob.ImportJobSpec.ImportJobScope.self, forKey: .scope)
      if let value = try container.decodeIfPresent(
        MetadataJob.ImportJobSpec.SyncMode.self, forKey: .entrySyncMode)
      {
        self.entrySyncMode = value
      }
      if let value = try container.decodeIfPresent(
        MetadataJob.ImportJobSpec.SyncMode.self, forKey: .aspectSyncMode)
      {
        self.aspectSyncMode = value
      }
      if let value = try container.decodeIfPresent(
        MetadataJob.ImportJobSpec.LogLevel.self, forKey: .logLevel)
      {
        self.logLevel = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sourceStorageUri, forKey: .sourceStorageUri)
      try container.encodeIfPresent(self.sourceCreateTime, forKey: .sourceCreateTime)
      try container.encodeIfPresent(self.scope, forKey: .scope)
      try container.encode(self.entrySyncMode, forKey: .entrySyncMode)
      try container.encode(self.aspectSyncMode, forKey: .aspectSyncMode)
      try container.encode(self.logLevel, forKey: .logLevel)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// A boundary on the scope of impact that the metadata import job can have.
    public struct ImportJobScope: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Required. The entry groups that are in scope for the import job,
      /// specified as relative resource names in the format
      /// `projects/{project_number_or_id}/locations/{location_id}/entryGroups/{entry_group_id}`.
      /// Only entries and aspects that belong to the specified entry groups are
      /// affected by the job.
      ///
      /// The entry groups and the job must be in the same location.
      public var entryGroups: [Swift.String] = []

      /// Required. The entry types that are in scope for the import job,
      /// specified as relative resource names in the format
      /// `projects/{project_number_or_id}/locations/{location_id}/entryTypes/{entry_type_id}`.
      /// The job modifies only the entries and aspects that belong to these
      /// entry types.
      ///
      /// If the metadata import file attempts to modify an entry whose type
      /// isn't included in this list, the import job is halted before modifying
      /// any entries or aspects.
      ///
      /// The location of an entry type must either match the location of the
      /// job, or the entry type must be global.
      public var entryTypes: [Swift.String] = []

      /// Optional. The aspect types that are in scope for the import job,
      /// specified as relative resource names in the format
      /// `projects/{project_number_or_id}/locations/{location_id}/aspectTypes/{aspect_type_id}`.
      /// The job modifies only the aspects that belong to these aspect types.
      ///
      /// This field is required when creating an aspect-only import job.
      ///
      /// If the metadata import file attempts to modify an aspect whose type
      /// isn't included in this list, the import job is halted before modifying
      /// any entries or aspects.
      ///
      /// The location of an aspect type must either match the location of the
      /// job, or the aspect type must be global.
      public var aspectTypes: [Swift.String] = []

      /// Optional. The glossaries that are in scope for the import job,
      /// specified as relative resource names in the format
      /// `projects/{project_number_or_id}/locations/{location_id}/glossaries/{glossary_id}`.
      ///
      /// While importing Business Glossary entries, the user must
      /// provide glossaries. While importing entries, the user does not have to
      /// provide glossaries. If the metadata import file attempts to modify
      /// Business Glossary entries whose glossary isn't included in this list,
      /// the import job will skip those entries.
      ///
      /// The location of a glossary must either match the location of the
      /// job, or the glossary must be global.
      public var glossaries: [Swift.String] = []

      /// Optional. The entry link types that are in scope for the import job,
      /// specified as relative resource names in the format
      /// `projects/{project_number_or_id}/locations/{location_id}/entryLinkTypes/{entry_link_type_id}`.
      /// The job modifies only the entryLinks that belong to these entry link
      /// types.
      ///
      /// If the metadata import file attempts to create or delete an entry link
      /// whose entry link type isn't included in this list, the import job will
      /// skip those entry links.
      public var entryLinkTypes: [Swift.String] = []

      /// Optional. Defines the scope of entries that can be referenced in the
      /// entry links.
      ///
      /// Currently, projects are supported as valid scopes.
      /// Format: `projects/{project_number_or_id}`
      ///
      /// If the metadata import file attempts to create an entry link
      /// which references an entry that is not in the scope, the import job will
      /// skip that entry link.
      public var referencedEntryScopes: [Swift.String] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ImportJobScope`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ImportJobScope().with { $0.entryGroups = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let entryGroups = CodingKeys(stringValue: "entryGroups")
        static let entryTypes = CodingKeys(stringValue: "entryTypes")
        static let aspectTypes = CodingKeys(stringValue: "aspectTypes")
        static let glossaries = CodingKeys(stringValue: "glossaries")
        static let entryLinkTypes = CodingKeys(stringValue: "entryLinkTypes")
        static let referencedEntryScopes = CodingKeys(stringValue: "referencedEntryScopes")

        static let _knownKeys: Set<Swift.String> = [
          "entryGroups",
          "entryTypes",
          "aspectTypes",
          "glossaries",
          "entryLinkTypes",
          "referencedEntryScopes",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .entryGroups) {
          self.entryGroups = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .entryTypes) {
          self.entryTypes = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .aspectTypes) {
          self.aspectTypes = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .glossaries) {
          self.glossaries = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .entryLinkTypes) {
          self.entryLinkTypes = value
        }
        if let value = try container.decodeIfPresent(
          [Swift.String].self, forKey: .referencedEntryScopes)
        {
          self.referencedEntryScopes = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.entryGroups, forKey: .entryGroups)
        try container.encode(self.entryTypes, forKey: .entryTypes)
        try container.encode(self.aspectTypes, forKey: .aspectTypes)
        try container.encode(self.glossaries, forKey: .glossaries)
        try container.encode(self.entryLinkTypes, forKey: .entryLinkTypes)
        try container.encode(self.referencedEntryScopes, forKey: .referencedEntryScopes)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataplex.v1.MetadataJob.ImportJobSpec.ImportJobScope"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Specifies how the entries and aspects in a metadata import job are
    /// updated. For more information, see [Sync
    /// mode](https://cloud.google.com/dataplex/docs/import-metadata#sync-mode).
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SyncMode: Codable, Equatable, Sendable {
      /// Sync mode unspecified.
      case unspecified
      /// All resources in the job's scope are modified. If a resource exists in
      /// Dataplex Universal Catalog but isn't included in the metadata import
      /// file, the resource is deleted when you run the metadata job. Use this
      /// mode to perform a full sync of the set of entries in the job scope.
      ///
      /// This sync mode is supported for entries.
      case full
      /// Only the resources that are explicitly included in the
      /// metadata import file are modified. Use this mode to modify a subset of
      /// resources while leaving unreferenced resources unchanged.
      ///
      /// This sync mode is supported for aspects.
      case incremental
      /// If entry sync mode is `NONE`, then aspects are modified according
      /// to the aspect sync mode. Other metadata that belongs to entries in the
      /// job's scope isn't modified.
      ///
      /// This sync mode is supported for entries.
      case `none`
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .full: return 1
        case .incremental: return 2
        case .`none`: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SYNC_MODE_UNSPECIFIED"
        case .full: return "FULL"
        case .incremental: return "INCREMENTAL"
        case .`none`: return "NONE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SyncMode/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SYNC_MODE_UNSPECIFIED": self = .unspecified
        case "FULL": self = .full
        case "INCREMENTAL": self = .incremental
        case "NONE": self = .`none`
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SyncMode/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .full
        case 2: self = .incremental
        case 3: self = .`none`
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("SYNC_MODE_UNSPECIFIED")
        case .full: return try container.encode("FULL")
        case .incremental: return try container.encode("INCREMENTAL")
        case .`none`: return try container.encode("NONE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The level of logs to write to Cloud Logging for this job.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum LogLevel: Codable, Equatable, Sendable {
      /// Log level unspecified.
      case unspecified
      /// Debug-level logging. Captures detailed logs for each import item. Use
      /// debug-level logging to troubleshoot issues with specific import items.
      /// For example, use debug-level logging to identify resources that are
      /// missing from the job scope, entries or aspects that don't conform to
      /// the associated entry type or aspect type, or other misconfigurations
      /// with the metadata import file.
      ///
      /// Depending on the size of your metadata job and the number of logs that
      /// are generated, debug-level logging might incur
      /// [additional costs](https://cloud.google.com/stackdriver/pricing).
      case debug
      /// Info-level logging. Captures logs at the overall job level. Includes
      /// aggregate logs about import items, but doesn't specify which import
      /// item has an error.
      case info
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .debug: return 1
        case .info: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "LOG_LEVEL_UNSPECIFIED"
        case .debug: return "DEBUG"
        case .info: return "INFO"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:LogLevel/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "LOG_LEVEL_UNSPECIFIED": self = .unspecified
        case "DEBUG": self = .debug
        case "INFO": self = .info
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:LogLevel/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .debug
        case 2: self = .info
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("LOG_LEVEL_UNSPECIFIED")
        case .debug: return try container.encode("DEBUG")
        case .info: return try container.encode("INFO")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.MetadataJob.ImportJobSpec"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Job specification for a metadata export job.
  public struct ExportJobSpec: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The scope of the export job.
    public var scope: MetadataJob.ExportJobSpec.ExportJobScope? = nil

    /// Required. The root path of the Cloud Storage bucket to export the
    /// metadata to, in the format `gs://{bucket}/`. You can optionally specify a
    /// custom prefix after the bucket name, in the format
    /// `gs://{bucket}/{prefix}/`. The maximum length of the custom prefix is 128
    /// characters. Dataplex Universal Catalog constructs the object path for the
    /// exported files by using the bucket name and prefix that you provide,
    /// followed by a system-generated path.
    ///
    /// The bucket must be in the same VPC Service Controls perimeter as the job.
    public var outputPath: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ExportJobSpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExportJobSpec().with { $0.scope = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let scope = CodingKeys(stringValue: "scope")
      static let outputPath = CodingKeys(stringValue: "outputPath")

      static let _knownKeys: Set<Swift.String> = [
        "scope",
        "outputPath",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.scope = try container.decodeIfPresent(
        MetadataJob.ExportJobSpec.ExportJobScope.self, forKey: .scope)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputPath) {
        self.outputPath = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.scope, forKey: .scope)
      try container.encode(self.outputPath, forKey: .outputPath)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The scope of the export job.
    public struct ExportJobScope: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Whether the metadata export job is an organization-level export job.
      ///
      /// - If `true`, the job exports the entries from the same organization and
      /// VPC Service Controls perimeter as the job. The project that the job
      /// belongs to determines the VPC Service Controls perimeter. If you set
      /// the job scope to be at the organization level, then don't provide a
      /// list of projects or entry groups.
      /// - If `false`, you must specify a list of projects or a list of entry
      /// groups whose entries you want to export.
      ///
      /// The default is `false`.
      public var organizationLevel: Swift.Bool = Swift.Bool()

      /// The projects whose metadata you want to export, in the format
      /// `projects/{project_id_or_number}`. Only the entries from
      /// the specified projects are exported.
      ///
      /// The projects must be in the same organization and VPC Service Controls
      /// perimeter as the job.
      ///
      /// If you set the job scope to be a list of projects, then set the
      /// organization-level export flag to false and don't provide a list of
      /// entry groups.
      public var projects: [Swift.String] = []

      /// The entry groups whose metadata you want to export, in the format
      /// `projects/{project_id_or_number}/locations/{location_id}/entryGroups/{entry_group_id}`.
      /// Only the entries in the specified entry groups are exported.
      ///
      /// The entry groups must be in the same location and the same VPC Service
      /// Controls perimeter as the job.
      ///
      /// If you set the job scope to be a list of entry groups, then set the
      /// organization-level export flag to false and don't provide a list of
      /// projects.
      public var entryGroups: [Swift.String] = []

      /// The entry types that are in scope for the export job, specified as
      /// relative resource names in the format
      /// `projects/{project_id_or_number}/locations/{location}/entryTypes/{entry_type_id}`.
      /// Only entries that belong to the specified entry types are affected by
      /// the job.
      public var entryTypes: [Swift.String] = []

      /// The aspect types that are in scope for the export job, specified as
      /// relative resource names in the format
      /// `projects/{project_id_or_number}/locations/{location}/aspectTypes/{aspect_type_id}`.
      /// Only aspects that belong to the specified aspect types are affected by
      /// the job.
      public var aspectTypes: [Swift.String] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ExportJobScope`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ExportJobScope().with { $0.organizationLevel = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let organizationLevel = CodingKeys(stringValue: "organizationLevel")
        static let projects = CodingKeys(stringValue: "projects")
        static let entryGroups = CodingKeys(stringValue: "entryGroups")
        static let entryTypes = CodingKeys(stringValue: "entryTypes")
        static let aspectTypes = CodingKeys(stringValue: "aspectTypes")

        static let _knownKeys: Set<Swift.String> = [
          "organizationLevel",
          "projects",
          "entryGroups",
          "entryTypes",
          "aspectTypes",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .organizationLevel) {
          self.organizationLevel = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .projects) {
          self.projects = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .entryGroups) {
          self.entryGroups = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .entryTypes) {
          self.entryTypes = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .aspectTypes) {
          self.aspectTypes = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.organizationLevel, forKey: .organizationLevel)
        try container.encode(self.projects, forKey: .projects)
        try container.encode(self.entryGroups, forKey: .entryGroups)
        try container.encode(self.entryTypes, forKey: .entryTypes)
        try container.encode(self.aspectTypes, forKey: .aspectTypes)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dataplex.v1.MetadataJob.ExportJobSpec.ExportJobScope"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.MetadataJob.ExportJobSpec"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Metadata job status.
  public struct Status: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. State of the metadata job.
    public var state: MetadataJob.Status.State = MetadataJob.Status.State()

    /// Output only. Message relating to the progression of a metadata job.
    public var message: Swift.String = Swift.String()

    /// Output only. Progress tracking.
    public var completionPercent: Swift.Int32 = Swift.Int32()

    /// Output only. The time when the status was updated.
    public var updateTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Status`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Status().with { $0.state = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let state = CodingKeys(stringValue: "state")
      static let message = CodingKeys(stringValue: "message")
      static let completionPercent = CodingKeys(stringValue: "completionPercent")
      static let updateTime = CodingKeys(stringValue: "updateTime")

      static let _knownKeys: Set<Swift.String> = [
        "state",
        "message",
        "completionPercent",
        "updateTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(MetadataJob.Status.State.self, forKey: .state) {
        self.state = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .message) {
        self.message = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .completionPercent) {
        self.completionPercent = value
      }
      self.updateTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.message, forKey: .message)
      try container.encode(self.completionPercent, forKey: .completionPercent)
      try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// State of a metadata job.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum State: Codable, Equatable, Sendable {
      /// State unspecified.
      case unspecified
      /// The job is queued.
      case queued
      /// The job is running.
      case running
      /// The job is being canceled.
      case canceling
      /// The job is canceled.
      case canceled
      /// The job succeeded.
      case succeeded
      /// The job failed.
      case failed
      /// The job completed with some errors.
      case succeededWithErrors
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .queued: return 1
        case .running: return 2
        case .canceling: return 3
        case .canceled: return 4
        case .succeeded: return 5
        case .failed: return 6
        case .succeededWithErrors: return 7
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .queued: return "QUEUED"
        case .running: return "RUNNING"
        case .canceling: return "CANCELING"
        case .canceled: return "CANCELED"
        case .succeeded: return "SUCCEEDED"
        case .failed: return "FAILED"
        case .succeededWithErrors: return "SUCCEEDED_WITH_ERRORS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "QUEUED": self = .queued
        case "RUNNING": self = .running
        case "CANCELING": self = .canceling
        case "CANCELED": self = .canceled
        case "SUCCEEDED": self = .succeeded
        case "FAILED": self = .failed
        case "SUCCEEDED_WITH_ERRORS": self = .succeededWithErrors
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .queued
        case 2: self = .running
        case 3: self = .canceling
        case 4: self = .canceled
        case 5: self = .succeeded
        case 6: self = .failed
        case 7: self = .succeededWithErrors
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .queued: return try container.encode("QUEUED")
        case .running: return try container.encode("RUNNING")
        case .canceling: return try container.encode("CANCELING")
        case .canceled: return try container.encode("CANCELED")
        case .succeeded: return try container.encode("SUCCEEDED")
        case .failed: return try container.encode("FAILED")
        case .succeededWithErrors: return try container.encode("SUCCEEDED_WITH_ERRORS")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.MetadataJob.Status"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Metadata job type.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Type_: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Import job.
    case `import`
    /// Export job.
    case export
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`import`: return 1
      case .export: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .`import`: return "IMPORT"
      case .export: return "EXPORT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "IMPORT": self = .`import`
      case "EXPORT": self = .export
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`import`
      case 2: self = .export
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
      case .`import`: return try container.encode("IMPORT")
      case .export: return try container.encode("EXPORT")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public enum OneOf_Spec: Codable, Equatable, Sendable {
    /// Import job specification.
    indirect case importSpec(MetadataJob.ImportJobSpec?)
    /// Export job specification.
    indirect case exportSpec(MetadataJob.ExportJobSpec?)
  }

  public enum OneOf_Result: Codable, Equatable, Sendable {
    /// Output only. Import job result.
    indirect case importResult(MetadataJob.ImportJobResult?)
    /// Output only. Export job result.
    indirect case exportResult(MetadataJob.ExportJobResult?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.MetadataJob"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
