// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Describes the format of the data within its storage location.
public struct StorageFormat: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The data format associated with the stored data, which
  /// represents content type values. The value is inferred from mime type.
  public var format: StorageFormat.Format = StorageFormat.Format()

  /// Optional. The compression type associated with the stored data.
  /// If unspecified, the data is uncompressed.
  public var compressionFormat: StorageFormat.CompressionFormat = StorageFormat.CompressionFormat()

  /// Required. The mime type descriptor for the data. Must match the pattern
  /// {type}/{subtype}. Supported values:
  ///
  /// - application/x-parquet
  /// - application/x-avro
  /// - application/x-orc
  /// - application/x-tfrecord
  /// - application/x-parquet+iceberg
  /// - application/x-avro+iceberg
  /// - application/x-orc+iceberg
  /// - application/json
  /// - application/{subtypes}
  /// - text/csv
  /// - text/<subtypes>
  /// - image/{image subtype}
  /// - video/{video subtype}
  /// - audio/{audio subtype}
  public var mimeType: Swift.String = Swift.String()

  /// Additional format-specific options.
  public var options: OneOf_Options? = nil

  /// Initialize a new instance of `StorageFormat`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StorageFormat().with { $0.format = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case format = "format"
    case compressionFormat = "compressionFormat"
    case mimeType = "mimeType"
    case csv = "csv"
    case json = "json"
    case iceberg = "iceberg"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.format = try container.decode(StorageFormat.Format.self, forKey: .format)
    self.compressionFormat = try container.decode(
      StorageFormat.CompressionFormat.self, forKey: .compressionFormat)
    self.mimeType = try container.decode(Swift.String.self, forKey: .mimeType)

    var options: OneOf_Options? = nil
    let optionsCheckAndSet = {
      if options != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'options'"))
      }
      options = $0
    }
    if let csv = try container.decodeIfPresent(StorageFormat.CsvOptions?.self, forKey: .csv) {
      try optionsCheckAndSet(.csv(csv))
    }
    if let json = try container.decodeIfPresent(StorageFormat.JsonOptions?.self, forKey: .json) {
      try optionsCheckAndSet(.json(json))
    }
    if let iceberg = try container.decodeIfPresent(
      StorageFormat.IcebergOptions?.self, forKey: .iceberg)
    {
      try optionsCheckAndSet(.iceberg(iceberg))
    }
    self.options = options
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.format, forKey: .format)
    try container.encode(self.compressionFormat, forKey: .compressionFormat)
    try container.encode(self.mimeType, forKey: .mimeType)

    if let choice = self.options {
      switch choice {
      case .csv(let value):
        try container.encode(value, forKey: .csv)
      case .json(let value):
        try container.encode(value, forKey: .json)
      case .iceberg(let value):
        try container.encode(value, forKey: .iceberg)
      }
    }
  }

  /// Describes CSV and similar semi-structured data formats.
  public struct CsvOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The character encoding of the data. Accepts "US-ASCII",
    /// "UTF-8", and "ISO-8859-1". Defaults to UTF-8 if unspecified.
    public var encoding: Swift.String = Swift.String()

    /// Optional. The number of rows to interpret as header rows that should be
    /// skipped when reading data rows. Defaults to 0.
    public var headerRows: Swift.Int32 = Swift.Int32()

    /// Optional. The delimiter used to separate values. Defaults to ','.
    public var delimiter: Swift.String = Swift.String()

    /// Optional. The character used to quote column values. Accepts '"'
    /// (double quotation mark) or ''' (single quotation mark). Defaults to
    /// '"' (double quotation mark) if unspecified.
    public var quote: Swift.String = Swift.String()

    /// Initialize a new instance of `CsvOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CsvOptions().with { $0.encoding = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.StorageFormat.CsvOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Describes JSON data format.
  public struct JsonOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The character encoding of the data. Accepts "US-ASCII", "UTF-8"
    /// and "ISO-8859-1". Defaults to UTF-8 if not specified.
    public var encoding: Swift.String = Swift.String()

    /// Initialize a new instance of `JsonOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = JsonOptions().with { $0.encoding = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.StorageFormat.JsonOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Describes Iceberg data format.
  public struct IcebergOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The location of where the iceberg metadata is present, must be
    /// within the table path
    public var metadataLocation: Swift.String = Swift.String()

    /// Initialize a new instance of `IcebergOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IcebergOptions().with { $0.metadataLocation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dataplex.v1.StorageFormat.IcebergOptions"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The specific file format of the data.
  public enum Format: Codable, Equatable, Sendable {
    /// Format unspecified.
    case unspecified
    /// Parquet-formatted structured data.
    case parquet
    /// Avro-formatted structured data.
    case avro
    /// Orc-formatted structured data.
    case orc
    /// Csv-formatted semi-structured data.
    case csv
    /// Json-formatted semi-structured data.
    case json
    /// Image data formats (such as jpg and png).
    case image
    /// Audio data formats (such as mp3, and wav).
    case audio
    /// Video data formats (such as mp4 and mpg).
    case video
    /// Textual data formats (such as txt and xml).
    case text
    /// TensorFlow record format.
    case tfrecord
    /// Data that doesn't match a specific format.
    case other
    /// Data of an unknown format.
    case unknown
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .parquet: return 1
      case .avro: return 2
      case .orc: return 3
      case .csv: return 100
      case .json: return 101
      case .image: return 200
      case .audio: return 201
      case .video: return 202
      case .text: return 203
      case .tfrecord: return 204
      case .other: return 1000
      case .unknown: return 1001
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "FORMAT_UNSPECIFIED"
      case .parquet: return "PARQUET"
      case .avro: return "AVRO"
      case .orc: return "ORC"
      case .csv: return "CSV"
      case .json: return "JSON"
      case .image: return "IMAGE"
      case .audio: return "AUDIO"
      case .video: return "VIDEO"
      case .text: return "TEXT"
      case .tfrecord: return "TFRECORD"
      case .other: return "OTHER"
      case .unknown: return "UNKNOWN"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Format/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "FORMAT_UNSPECIFIED": self = .unspecified
      case "PARQUET": self = .parquet
      case "AVRO": self = .avro
      case "ORC": self = .orc
      case "CSV": self = .csv
      case "JSON": self = .json
      case "IMAGE": self = .image
      case "AUDIO": self = .audio
      case "VIDEO": self = .video
      case "TEXT": self = .text
      case "TFRECORD": self = .tfrecord
      case "OTHER": self = .other
      case "UNKNOWN": self = .unknown
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Format/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .parquet
      case 2: self = .avro
      case 3: self = .orc
      case 100: self = .csv
      case 101: self = .json
      case 200: self = .image
      case 201: self = .audio
      case 202: self = .video
      case 203: self = .text
      case 204: self = .tfrecord
      case 1000: self = .other
      case 1001: self = .unknown
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .parquet: return try container.encode(1)
      case .avro: return try container.encode(2)
      case .orc: return try container.encode(3)
      case .csv: return try container.encode(100)
      case .json: return try container.encode(101)
      case .image: return try container.encode(200)
      case .audio: return try container.encode(201)
      case .video: return try container.encode(202)
      case .text: return try container.encode(203)
      case .tfrecord: return try container.encode(204)
      case .other: return try container.encode(1000)
      case .unknown: return try container.encode(1001)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The specific compressed file format of the data.
  public enum CompressionFormat: Codable, Equatable, Sendable {
    /// CompressionFormat unspecified. Implies uncompressed data.
    case unspecified
    /// GZip compressed set of files.
    case gzip
    /// BZip2 compressed set of files.
    case bzip2
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .gzip: return 2
      case .bzip2: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "COMPRESSION_FORMAT_UNSPECIFIED"
      case .gzip: return "GZIP"
      case .bzip2: return "BZIP2"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CompressionFormat/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "COMPRESSION_FORMAT_UNSPECIFIED": self = .unspecified
      case "GZIP": self = .gzip
      case "BZIP2": self = .bzip2
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CompressionFormat/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .gzip
      case 3: self = .bzip2
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .gzip: return try container.encode(2)
      case .bzip2: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Additional format-specific options.
  public enum OneOf_Options: Codable, Equatable, Sendable {
    /// Optional. Additional information about CSV formatted data.
    indirect case csv(StorageFormat.CsvOptions?)
    /// Optional. Additional information about CSV formatted data.
    indirect case json(StorageFormat.JsonOptions?)
    /// Optional. Additional information about iceberg tables.
    indirect case iceberg(StorageFormat.IcebergOptions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.StorageFormat"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
