// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for UpdateEntryLink method.
public struct UpdateEntryLinkRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Entry Link resource.
  public var entryLink: EntryLink? = nil

  /// Optional. If set to true and the entry link doesn't exist, the service will
  /// create it.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Optional. The map keys of the Aspects which the service should modify.
  /// It should be the aspect type reference in the format
  /// `{project_id_or_number}.{location_id}.{aspect_type_id}`.
  ///
  /// If this field is left empty, the service treats it as specifying
  /// exactly those Aspects present in the request.
  public var aspectKeys: [Swift.String] = []

  /// Initialize a new instance of `UpdateEntryLinkRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateEntryLinkRequest().with { $0.entryLink = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.UpdateEntryLinkRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
