// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Update Entry request.
public struct UpdateEntryRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Entry resource.
  public var entry: Entry? = nil

  /// Optional. Mask of fields to update. To update Aspects, the update_mask must
  /// contain the value "aspects".
  ///
  /// If the update_mask is empty, the service will update all modifiable fields
  /// present in the request.
  public var updateMask: GoogleWKT.FieldMask? = nil

  /// Optional. If set to true and the entry doesn't exist, the service will
  /// create it.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Optional. If set to true and the aspect_keys specify aspect ranges, the
  /// service deletes any existing aspects from that range that weren't provided
  /// in the request.
  public var deleteMissingAspects: Swift.Bool = Swift.Bool()

  /// Optional. The map keys of the Aspects which the service should modify. It
  /// supports the following syntaxes:
  ///
  /// * `<aspect_type_reference>` - matches an aspect of the given type and empty
  /// path.
  /// * `<aspect_type_reference>@path` - matches an aspect of the given type and
  /// specified path. For example, to attach an aspect to a field that is
  /// specified by the `schema` aspect, the path should have the format
  /// `Schema.<field_name>`.
  /// * `<aspect_type_reference>@*` - matches aspects of the given type for all
  /// paths.
  /// * `*@path` - matches aspects of all types on the given path.
  ///
  /// The service will not remove existing aspects matching the syntax unless
  /// `delete_missing_aspects` is set to true.
  ///
  /// If this field is left empty, the service treats it as specifying
  /// exactly those Aspects present in the request.
  public var aspectKeys: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UpdateEntryRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateEntryRequest().with { $0.entry = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let entry = CodingKeys(stringValue: "entry")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let allowMissing = CodingKeys(stringValue: "allowMissing")
    static let deleteMissingAspects = CodingKeys(stringValue: "deleteMissingAspects")
    static let aspectKeys = CodingKeys(stringValue: "aspectKeys")

    static let _knownKeys: Set<Swift.String> = [
      "entry",
      "updateMask",
      "allowMissing",
      "deleteMissingAspects",
      "aspectKeys",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.entry = try container.decodeIfPresent(Entry.self, forKey: .entry)
    self.updateMask = try container.decodeIfPresent(GoogleWKT.FieldMask.self, forKey: .updateMask)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowMissing) {
      self.allowMissing = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .deleteMissingAspects) {
      self.deleteMissingAspects = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .aspectKeys) {
      self.aspectKeys = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.entry, forKey: .entry)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encode(self.allowMissing, forKey: .allowMissing)
    try container.encode(self.deleteMissingAspects, forKey: .deleteMissingAspects)
    try container.encode(self.aspectKeys, forKey: .aspectKeys)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.dataplex.v1.UpdateEntryRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
